KMKfw/kmk_firmware

.ampy, .gitmodules, Makefile, Pipfile, Pipfile.lock, boards/klardotsh/twotwo_matrix_feather.py, entrypoints/feather_nrf52832.py, kmk/circuitpython/matrix.py, kmk/circuitpython/util.py, kmk/common/consts.py, kmk/common/keymap.py, setup.cfg
It can even auto-deploy to my Feather in a single Makefile step
You'll need `python-pipenv` on Arch to use this in any reasonable fashion.
Currently don't have unit tests/PR lint checks enabled. They're coming soon/eventually.
=> Repo setup and a basic matrix-scan-then-do-nothing keyboard

.gitmodules, Makefile, entrypoints/teensy31.py
Added microcontroller support. Keyboard support coming later in another PR.
=> Teensy support

kmk/common/keycodes.py
Set better keycode values for KC_NO and KC_TRANSPARENT which is an alias to KC_TRNS
=> Small keycode change

kmk/common/internal_keycodes.py, linux-udev/99-stm-bootloader.rules, user_keymaps/kdb424/handwire_planck_pyboard.py, user_keymaps/klardotsh/threethree_matrix_pyboard.py
=> Topic grave escape

kmk/common/event_defs.py, kmk/common/internal_keycodes.py, kmk/common/internal_state.py, kmk/common/keycodes.py, kmk/common/kmktime.py, user_keymaps/kdb424/handwire_planck_pyboard.py, user_keymaps/klardotsh/threethree_matrix_pyboard.py
We need to convert at least TT to tap dance, but holding the rest back for that is not something I would call needed.
=> Advanced layers support basically done.

kmk/common/keycodes.py
Save CPU cycles and RAM at bootup (deferred to first usage, although the CPU hit is higher at that usage time by a bit) all in one go. Should reduce heap thrashing tremendously on boot since you're probably not using all several hundred KC_ objects on a single board, and if you are, you're already accepting the RAM hit.
=> Make KC object lazy but cached to avoid huge AttrDict compilation (most keycodes probably are not used anyway)

user_keymaps/kdb424/handwire_planck_featherm4.py, util/bootloader.py, util/reset.py
The klanck is now running on a feather.
=> Add new keyboard now on Circuitpython.

docs/leader.md, kmk/firmware.py
Oops, #74 went through without supporting documentation. Fixed!
=> Update docs for leader mode

.gitignore, docs/split_keyboards.md, kmk/firmware.py, user_keymaps/kdb424/levinson_m4.py
This is a solid start to #3 bringing a solid base for i2c and bluetooth to come later.
=> Topic split keyboards

hardware/itsy_bitsy_to_pro_micro.brd
This removes the annoying sharp corner and "JP5" on the bottom silk.
=> fixing small silk and outilne issue

hardware/itsy_bitsy_to_pro_micro.brd
I marked the pro-micro's TX and RAW pins at Josh's suggestion to make the orientation a bit easer to determine.
=> added notes to identify the pro-micro orientation

docs/split_keyboards.md, kmk/firmware.py, user_keymaps/kdb424/levinson_m4.py, user_keymaps/kdb424/nyquist_converter.py
=> Unbrick splits

user_keymaps/kdb424/nyquist_converter.py
Just a keymap fix that rebased incorrectly.
=> This failed to properly rebase

docs/keycodes.md, docs/modtap.md, kmk/firmware.py, kmk/handlers/modtap.py, kmk/keys.py, kmk/types.py
=> Added mod tap with docs

README.md
It's not particularly useful - we haven't run into any weirdness around contributions and it's a hurdle to contributing that shouldn't need to be there.
The bot and merge-blocking check have also been disabled.
=> Goodbye, CLA!

user_keymaps/kdb424/luddite.py, user_keymaps/kdb424/nyquist_r2.py
Personal layout changes. Assuming I didn't break spec, should be easy merge.
=> layout changes

user_keymaps/kdb424/nyquist_r2.py
=> layout update

docs/rgb.md
Very small docs cleanup. Was missing a line in RGB.
=> small docs add for rgb

kmk/rgb.py
=> Fix animation speed

docs/keycodes.md, kmk/ble.py, kmk/handlers/stock.py, kmk/keys.py, user_keymaps/dzervas/lab68.py
With the key `BT_CLEAR_BONDS` all of the stored bondings are cleared! :smile:
=> [BLE] Clear bonds

kmk/boards/nice_nano/crkbd.py, user_keymaps/default/nice_nano/crkbd.py
Tested 100% working. Will just merge.
=> Topic corne nicenano

kmk/boards/nice_nano/crkbd.py, kmk/keys.py, kmk/kmk_keyboard.py, kmk/matrix.py, user_keymaps/kdb424/corne.py
Reduces boot times by half, and boots fine even on the M4.
=> Remove GC. Not needed on newer Cpy versions

docs/split_keyboards.md, kmk/boards/nice_nano/crkbd.py, kmk/keys.py, kmk/kmk_keyboard.py, kmk/matrix.py
Wording change to go along with world trends on open source code. Simple wording change, no functionality changed at all.
=> Switch to initiator/target

kmk/kmk_keyboard.py, kmk/rgb.py
Cpy got a lot faster, allowing us to do animations less often, and more smoothly. This should be a simple change before the full split refactor.
=> update RGB for more modern cpy versions

.github/workflows/test.yml, Pipfile, Pipfile.lock, kmk/ble.py, kmk/led.py, kmk/matrix.py, kmk/rgb.py, setup.cfg
Yeah, so anyway, these four commits get at least pre-merge CI working again, as well as `make test` locally assuming the dev has pipenv set up correctly
=> The CI Error Rate Is Too Damn High (and this meme is ancient)

boards/crkbd/kb_rp2040.py, boards/crkbd/main.py, kmk/keys.py, kmk/modules/split.py, user_keymaps/kdb424/corne.py
Things like shifted keys were broken, and added support for the RP2040 Pro micro to the corne. This resolves both of those.
=> Fix many broken keys

boards/atreus62/README.md, boards/atreus62/kb.py, boards/atreus62/main.py, docs/encoder.md, kmk/modules/encoder.py
Here is my stab at a module for encoders.  It is tested a and working on an Atreus62 with a single encoder.  I really like the modular design of this new branch, this was pretty easy to do once I got my head wrapped around it.
=> Encoder module!

boards/crkbd/README.md
=> typo in corne readme

docs/ja/Getting_Started.md
=> Translated Getting_Started.md to Japanese.

docs/ptBR/Getting_Started.md, docs/ptBR/Officially_Supported_Microcontrollers.md, docs/ptBR/kmkpython_vs_circuitpython.md
Hello! I want to contribute to this project by providing translations for the documentation.
=> Brazilian Portuguese translations

docs/handwiring.md
(Really)Minor changes:
- The Supported Microcontroller URL was broken, fixed that
- Added a space for cleaner look between text and link
=> Corrected a URL typo

kmk/keys.py
=> add / to key names

kmk/handlers/sequences.py
=> Fix send_string (#206)

kmk/handlers/stock.py, kmk/kmk_keyboard.py, kmk/kmktime.py, kmk/modules/encoder.py, kmk/modules/layers.py, kmk/modules/modtap.py, kmk/modules/power.py, kmk/modules/split.py
=> Convert to supervisor ticks

kmk/kmk_keyboard.py
=> fix tapdancing

kmk/modules/layers.py
Fixed a problem where layer switching was not working in LT().
=> Fix LT() doesn't work

kmk/keys.py
I guess a copy paste mistake from the previous line.
=> Fix Key no_release argument

kmk/handlers/sequences.py
Same issue as #206 fixed by #233.
=> fix unicode sequence

boards/navi10/README.md, boards/navi10/kb.py, boards/navi10/main.py
Hey!
First time I've contributed here, so let me know if I'm doing anything wrong. Thanks :)
\- Eva
=> Added navi10 by u/emdarcher

boards/navi10/kb.py
I forgot to add the code to turn on the LED, this PR adds it.
=> Added navi10 led

README.md, kmk/hid.py, kmk/kmk_keyboard.py, kmk/modules/holdtap.py, tests/__init__.py, tests/keyboard_test.py, tests/mocks.py, tests/test_hold_tap.py, tests/test_kmk_keyboard.py
I have added a few unit tests that can be executed without having a board at hand. There're still many features that aren't covered yet, but I guess it's a start.
=> unit tests for execution in desktop dev environment

kmk/kmk_keyboard.py
cleaned up from #311, this PR should be good to merge
=> Fix for dropping keys on split boards

docs/layers.md, docs/modtap.md, kmk/key_validators.py, kmk/kmk_keyboard.py, kmk/modules/__init__.py, kmk/modules/holdtap.py, kmk/modules/layers.py, kmk/modules/modtap.py, kmk/modules/tapdance.py, kmk/types.py, tests/test_hold_tap.py
This has been a requested feature (#278), and after using it for 2 days, rightfully so.
Just wanted you to know that this is being worked on.
=> hold-tap-enhancements

docs/Getting_Started.md, docs/README.md, docs/extensions.md, docs/modules.md
I don't know if this is right approach, but an index was something I missed during early KMK adoption. I know that list of files is an index on itself, but it's not categorized.
Inspired by #336 issue, which was looking for already existing documentation.
=> Add doc index

docs/rgb.md, kmk/extensions/rgb.py
Ties RGB animation speed to supervisor ticks, instead of main loop execution frequency.
=> animation speed based on system timer

docs/Getting_Started.md, docs/Officially_Supported_Microcontrollers.md, docs/README.md, docs/ja/Getting_Started.md, docs/kmkpython_vs_circuitpython.md, docs/ptBR/Getting_Started.md, docs/ptBR/ble_hid.md
KMKpython is broken and unupported. Docs needed an update.
=> Remove KMKpython reference

.gitignore, docs/layers.md, docs/midi.md, docs/modules.md, kmk/modules/midi.py
Adds the `midi.py` module assembled by xs5871 on Discord/Matrix and includes the `modules.md` and `midi.md` documentation for implementing it.
=> MIDI module and docs

docs/README.md, docs/combos.md, docs/modules.md, kmk/kmk_keyboard.py, kmk/modules/combos.py, tests/test_combos.py
I'd like to submit this for discussion.
It's not quite as broad as the swallow API mentioned in #222, but I think it's generalized enough to be able to handle most multi-key functionality. Commit includes documentation, so I won't go into details about features.
I don't mind keeping this PR open for a while. I stumbled upon some scaling and consistency issues with our current timeout API that I started working on that on the side.
=> implement combo/chord/sequence module

docs/easypoint.md, docs/modules.md, kmk/modules/easypoint.py
Simple module for supporting the AS5013 Easypoint over I2C.
=> Support for AS5013 aka. Easypoint

kmk/handlers/stock.py, kmk/hid.py, kmk/keys.py, kmk/modules/split.py
Now: BLE Split not works
@Tonasz fixed: BLE Split works with USB HID (from #328)
I fixed: BLE Split works with BLE HID
=> Enabling Completely Wireless

kmk/kmk_keyboard.py
During timeout processing, cancelations have to take immediate effect,
but new 0-delay timeouts have to be moved to the next cycle.
=> fix failing unit test.

boards/sofle/sofleV2/README.md, boards/sofle/sofleV2/kb.py, boards/sofle/sofleV2/main.py
Added support for SofleV2 using the SparkFun Pro Micro RP2040
=> Add Support for SofleV2

docs/cg_swap.md, kmk/modules/cg_swap.py, kmk/modules/swap_keys.py
Another qmk inspired feature which allows swapping control with cmd and vice versa
Helpful when using the keyboard on mac and windows
=> swapping control with cmd

docs/cg_swap.md
Missed the keys usage in the docs, please merge this update too
=> Updated doc to show the keys usage for cg swap

docs/capsword.md, kmk/modules/capsword.py
This is a similar feature available in some of the forks of qmk allowing to break out of caps lock if you type keys that break the word
Please review and provide feedback if this is in the correct direction
This is my first contribution as I am learning Python and experimenting with the kb2040 I got recently
=> caps word implementation

kmk/scanners/native_keypad_scanner.py
Rebased #373 and rebased to pass test.
=> Levpopov direct gpio split fix

kmk/modules/oneshot.py, tests/test_hold_tap.py
Resolves #387 (potentially).
Would be great if @ldsands could verify before merging.
=> fix late release of oneshot keys

docs/scanners.md, kmk/kmk_keyboard.py, kmk/modules/split.py, kmk/scanners/__init__.py, kmk/scanners/digitalio.py, kmk/scanners/encoder.py, kmk/scanners/keypad.py
Native matrix events from an encoder, because, why not. Only makes sense in conjunction with #400.
Also specifically not meant to compete with or supersede the encoder module.
=> Feature scanner encoder

kmk/kmk_keyboard.py
Factor out the module `process_key` into `keyboard.pre_process_key` + minor refactor.
This is preliminary to facilitate #413.
=> Refactor process key

docs/rgb.md, kmk/extensions/rgb.py
We already support "custom" pixelbuffer, now we also support more than one of those.
=> implement multiple pixelbuffer in rgb extension

kmk/kmk_keyboard.py
Some of the debug messages in kmk_keyboard weren't reflecting what was happening.
=> Align debug messages with method called

docs/keys.md
* linked named files for ease of access
* updated directories (ex. kmk/internal_state.py -> kmk/kmk_keyboard.py)
=> Updated directories and added links to keys.py

docs/Getting_Started.md
I'm tired of seeing these comments everywhere in people's code, and it's not relevant to most of them.
=> cleanup comments

kmk/extensions/rgb.py
The `pixels` reference didn't always point to the correct pixelbuffer. Something, something, stale reference..
=> fix dangling reference issue

kmk/extensions/rgb.py
Reverts KMKfw/kmk_firmware#471
More coffee, less merging in the morning.
=> Revert "[rgb] fix set_rgb_fill method"

docs/mouse_keys.md
Improved consistency and clarity by bringing keycode representation in line with other documentation containing keycodes.
=> Improve clarity in mouse_keys.md

docs/porting_to_kmk.md, docs/split_keyboards.md
A few small things I changed who helped me to setup my keyboard. I guess it might help others.
=> Make things easier to setup

README.md
and fixed spacing of shields.
fixes #463
=> Adds link to Documentation in README.md

docs/config_and_keymap.md
Fixed a missing closing bracket in the documentation
=> Fixed missing closing bracket

docs/Getting_Started.md
=> Update Getting_Started.md - typo

kmk/modules/combos.py, tests/keyboard_test.py
Let's see if this still fails.
=> unit test fail may be caused by a stuck combo

docs/keycodes.md, docs/media_keys.md, docs/ptBR/keycodes.md, docs/ptBR/media_keys.md, kmk/extensions/media_keys.py, kmk/keys.py
=> Enhancement mediakeys

kmk/keys.py
finishing up #430.
may resolve #516 (saves a bit of space on the stack), if not, makes it easier to fix afterwards.
=> Extract key generators

docs/split_keyboards.md, kmk/transports/pio_uart.py
=> remove adafruit_pioasm dependency

kmk/handlers/stock.py, kmk/key_validators.py, kmk/keys.py, kmk/kmk_keyboard.py, kmk/modules/holdtap.py, kmk/modules/layers.py, kmk/modules/modtap.py, kmk/modules/oneshot.py, kmk/modules/tapdance.py, kmk/types.py
A bit of cleanup. Remove some unused bits and move some of the types/validators into the modules where they are actually used.
=> Cleanup general

docs/scanners.md
=> Fix hyperlink in scanners.md

docs/pimoroni_trackball.md, kmk/modules/pimoroni_trackball.py
I added the good old reverse scrolling mode.
Scrolling parameter is optional, defaults to natural scrolling direction.
=> Add reverse scrolling mode to the Pimoroni Trackball module

kmk/modules/mouse_keys.py
resolves #534.
Quick and dirty fix to get mouse keys working at all, at least.
=> fix mouse_keys not working at all

docs/lock_status.md, kmk/extensions/lock_status.py
Add a callback to lock status so that thing  such as LEDs can be kept in sync.
=> Docs: How to react to lock status changes

boards/fingerpunch/ffkb/nice_nano/main.py, user_keymaps/TellNoLies/lily58.py
Move keymap to proper spot, and fix the formatting/isort
=> Move keymap to proper spot

boards/boardsource/Lulu/README.md
I can't seem to get this correct. Glad I know how to read only *after* the merge button is hit. Seems clean this time I think. Copy mistakes are the most common mistakes I find.
=> More Lulu cleanup

.gitignore
This is just some housekeeping, to update gitignore from GitHub's project. I ran into new tracked files while playing with `nox`, `pdm`, `invoke`, etc.
=> updade gitignore from gh

kmk/modules/combos.py
This refactor makes code readability and performance improvements.
=> Refactor combos

kmk/modules/holdtap.py
=> add debug info for holdtap key resolution

docs/peg_rgb_matrix.md, kmk/extensions/peg_oled_display.py, kmk/extensions/peg_rgb_matrix.py
- Improve Peg OLED extension performance (remove flicker/flash when changing content based on current layer).
- Update Peg RGB extension to support RGB LED brightness change and add two keycodes to increase/decrease brightness.
=> Peg module performance improvements

docs/rgb.md
Bring rgb docs somewhat up-to-date. It's likely I missed something, but at least it's not all completely out-of-date.
=> bring rgb docs somewhat up-to-date

kmk/kmk_keyboard.py
Previously only secondary_matrix_update was set on sandbox.
=> Set sandbox.matrix_update

docs/layers.md
Very common question, very simple answer.
Comments and suggestions welcome
=> Howto RGB Layers

boards/pimoroni/keybow/keybow.py
Replacement PR for #606 to fix formatting.
=> added Raspberry Pi Pico pinouts for the Pimoroni Keybow: Maintainer edit

docs/modtap.md, kmk/modules/holdtap.py, tests/test_hold_tap.py
addresses the issues identified in #619, without partial regression of functionality.
=> implement multiple-choice for holdtap repeat

docs/en/scanners.md
There was confusion about this, so hopefully this comment will help.
=> Update debounce docs

docs/en/quickpin.md
Merged the docs change, and this got left behind. Putting in the proper new home.
=> Move quickpin docs

boards/ferris_sweep/README.md, boards/ferris_sweep/kb.py, boards/ferris_sweep/main.py
Hi, this PR adds support for the Ferris Sweep keyboard. I hope the files are all in order.
PS. This is my first time using KMK and it's been a pleasure to get up and running with it. Thanks for all the work that's gone into it!
=> Ferris sweep

docs/en/peg_oled_display.md
Add some clarity for people new to KMK on which files should contain the given changes.
=> [docs] Make changed files clearer

kmk/modules/layers.py
Key creation formatting in layer module wasn't consistent across keys in the module or with key creation in other parts of the codebase.
=> Re-formatted layer key creation to be consistent

kmk/extensions/rgb.py
=> Remove erroneous argument from `hsv_to_rgbw` conversion function

docs/en/layers.md
The advanced example was missing a self argument
=> Correct advanced layers example

kmk/keys.py
Instead of relying on the uncontrollable availability of a big chunk of contiguous memory for key caching, we can manually fragment the cache into reasonably small partitions. This will get rid of the out-of-memory-during-reallocation issues when `KC.__cache` grows. That means we can also finally purge the stack size cap from `boot.py`.
=> Split KeyAttrDict.__cache into memory friendly partitions.

kmk/handlers/stock.py, kmk/keys.py
=> Add BLE_DISCONNECT key

kmk/hid.py
=> Fix cc hid report

docs/en/mouse_keys.md, kmk/modules/mouse_keys.py
Add keys for mouse buttons 4 and 5. CPs default pointing device HID report doesn't support more than that.
=> Feature more mouse keys

Makefile, docs/en/contributing.md
Couple of minor enhancements to the `Makefile` that make my work easier.
=> Enhancement: Makefile

kmk/modules/power.py
The last update to this module used new at the time ```check_deadline``` function wrong, I seem to have fixed this.
=> Fix power.py module

kmk/kmk_keyboard.py
=> Clear HID reports on crash

kmk/kmk_keyboard.py, kmk/modules/holdtap.py, tests/test_holdtap.py
Working on #740 I noticed a few inconsistencies with stacked holdtaps.
=> Fix some old holdtap inconsistencies

tests/test_holdtap.py, tests/test_tapdance.py
Continuation of #731; apparently I missed a few.
=> Speed up unit tests

kmk/modules/combos.py
Looks like we applied a key-release twice.
maybe resolves #738
=> Fix oneshot as combo result getting stuck

boards/anavi/knob1/code.py
Remove print to cleanup the code.
=> boards/anavi/knob1/code.py: Cleanup

kmk/extensions/oled.py
Fixed a silly oversight that was preventing image entries from working
=> Fix OLED ImageEntry

kmk/hid.py, kmk/modules/autoshift.py, kmk/scheduler.py, tests/test_autoshift.py
addresses #665.
Potential users: please verify and report any unexpected or unwanted behavior.
=> Feature: autoshift

kmk/extensions/lock_status.py
* reduce memory consumption
* move hardware init to `during_bootup`
* simplify report check
=> Refactor lock_status extension

boards/dactyl_manuform/readme.md
- 1 link changed
- wording tidied
=> Update `dactyl_manuform` readme

docs/en/boot.md, kmk/bootcfg.py, kmk/hid.py, kmk/hid_reports/nkro_keyboard.py
Add n-key rollover support, depends on #730.
=> Feature nkro

boards/draculad/README.md, boards/draculad/kb.py, boards/draculad/main.py
=> `Draculad` board: corrections applied to pass linter

kmk/modules/pimoroni_trackball.py
Various memory and performance improvements.
resolves: #649
=> Refactor pimoroni trackball

kmk/modules/mouse_keys.py
Look what I found, lying around for weeks on my "PR this" list.
* tiny bit of memory optimisation
* use task queue instead of periodic timer
* code deduplication
=> Refactor MouseKeys

.github/workflows/test.yml, Pipfile, docs/en/contributing.md
Unit tests suddenly started failing. Good time to move on from python3.9.
=> Bump python version to 3.11 to make it compatible with current flake8

.github/workflows/test.yml, Pipfile, boards/dactyl_tracer/README.md, boards/dactyl_tracer/kb.py, boards/dactyl_tracer/main.py, docs/en/README.md, docs/en/config_and_keymap.md, docs/en/contributing.md, docs/en/keycodes.md, docs/en/keys.md, docs/en/kmkpython_vs_circuitpython.md, docs/en/oneshot.md, docs/en/rapidfire.md
=> Fixes links in documentation for website rendering

docs/en/mouse_keys.md, kmk/modules/mouse_keys.py
Exposing variables as arguments in MouseKeys module
=> Mouse keys movement docs

kmk/hid.py
=> Fix BLE init error

README.md, docs/en/contributing.md
=> Link to contributing in README.md

docs/en/Getting_Started.md
=> Update docs to bump minimum circuitpython version to 7.3

docs/en/split_keyboards.md
=> Update ee hands to mention required pins

docs/en/Officially_Supported_Microcontrollers.md
This PR is very opinionated, but as far as I can see it is out of scope for kmk to implement support for ble on certain, so I would suggest to 
close #785 
with this PR. I am gonna follow up with a PR to #634 to point questions about hardware support to zulip, but I did not want to polute this PR with two issues.
=> Add some ble details to docs in regards to controller compatibility

docs/en/quickpin.md
=> update supported controllers in `quickpin.md`

kmk/scheduler.py
=> Fix scheduler lock up on long periodic tasks

boards/osprette/README.md, boards/osprette/kb.py, boards/osprette/main.py
Keymap based o the Sweep, but matrix ported to osprette. Seems to be working as intended.
=> feat: Add Osprette

user_keymaps/ZFR_KBD/RP2.65-F.py
Tested in version of circuit python 7.*
=> To UP and Down volumn use keyboard.tap_key insted of hid_report

tests/keyboard_test.py, tests/task.py, tests/test_scheduler.py
=> Add unit testing for the scheduler

boards/boardsource/unicorne/README.md, boards/boardsource/unicorne/kb.py, boards/boardsource/unicorne/main.py
Will come back and offer a follow up PR for images and buy links when there is a store page and official photos, but some are in the wild already, hence the "early" PR.
=> feat: Add Boardsouce Unicorne

kmk/kmk_keyboard.py, kmk/modules/power.py
=> Cleanup _i2c_deinit_count

util/spellcheck.sh
Shows spelling mistakes and their respective line of occurance.
=> Add found "bad words" to the output of `spellcheck.sh`

kmk/kmk_keyboard.py, tests/test_kmk_keys.py
Addresses https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/Combos.20with.20match_coord.3DTrue
=> Fix dropping keypress if resolved to `KC.TRNS`

kmk/kmk_keyboard.py
Make the 'Unexpected error' message slightly more helpfull.
=> Show content of unexpected error

docs/en/README.md, docs/en/steno.md, kmk/modules/steno.py
Adds a module for communicating with stenography software over serial.
=> Add steno module

docs/en/pimoroni_trackball.md
Extended documentation with a code snippet how to animate the trackball LED.
=> Extended documentation for the trackball LED animated light

kmk/extensions/international.py, kmk/modules/combos.py, kmk/modules/holdtap.py, kmk/modules/layers.py, kmk/modules/pimoroni_trackball.py, kmk/modules/split.py, kmk/scanners/digitalio.py, kmk/transports/pio_uart.py, tests/test_string_substitution.py, util/compile.py
Changes necessary to facilitate #948.
I also refactored (removed) inline `if`'s. They're hard to read and black 24 makes them even worse to look at.
=> Fix black bump

kmk/kmk_keyboard.py
=> Cleanup old timeout code

kmk/modules/pimoroni_trackball.py
Throws an error when running cleanup.
=> Fix PixelBuf has no deinit

docs/en/layers.md
This comes up constantly and could benefit from a better example.
=> Improve docs on Layers + RGB

docs/en/macros.md, kmk/modules/macros.py, tests/test_macros.py
=> Extend macros with hold and release handlers

kmk/modules/holdtap.py, tests/test_holdtap.py
=> Fix retaining key release from rolls into HT

docs/en/README.md
=> Fix snapshot link in README.md

kmk/keys.py
=> Fix syntax error with mpy-cross-8.x

kmk/modules/macros.py, tests/test_macros.py
See [chat](https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/Creating.20a.20Macro.20-.20Alt.20.2B.20Tab.20.2F.20Application.20Switcher) for reference.
=> Fix inconsistent macro state when double tapping

kmk/modules/capsword.py, tests/test_capsword.py
=> Fix Capsword handling of special keys

tests/keyboard_test.py
Fix failing unit tests for #2657
=> Fix extensions in KeyboardTest isn't of type list

docs/en/pimoroni_trackball.md
The trackball docs are pretty terrible in every regard and I don't feel like rewriting them from scratch right now.
Here's some missing documentation, which is at least some kind of progress...
=> Add docs for pimoroni trackball handlers

kmk/modules/tapdance.py, tests/test_tapdance.py
=> Fix dependency of TapDance on instantiated HoldTap

kmk/scanners/keypad.py
=> Fix keypad scanner init

boards/a_dux/kb.py, boards/anavi/anavi-arrows/arrows.py, boards/anavi/knob1/code.py, boards/anavi/knobs3/code.py, boards/budgy/kb.py, boards/ferris_sweep/kb.py, boards/isopad/kb.py, boards/pimoroni/keybow/keybow.py, boards/pimoroni/keybow_2040/keybow_2040.py, docs/en/scanners.md
Issue reported [here](https://github.com/KMKfw/kmk_firmware/pull/1044#issuecomment-2544210463) and identified in the next message.
=> Fix scanners.md

kmk/scanners/__init__.py
=> Fix DiodeOrientation to columns_to_anodes mapping

boards/anavi/macro-pad-12/README.md
Fix the link to the documentation for the display.
=> boards/anavi/macro-pad-12/README.md: Fix link

kmk/hid_reports/pointer.py
=> Fix custom hid pointer report

kmk/kmk_keyboard.py, kmk/modules/sticky_keys.py, kmk/modules/tapdance.py, tests/test_tapdance.py
=> Fix inconsistencies with TD on momentary layers

kmk/modules/analogin.py
As reported in https://kmkfw.zulipchat.com/#narrow/channel/370377-drivers-and-hardware/topic/Analog.20input.20support/near/499020462
=> fix(analogin): fix evtmap memoization

boards/psion/README.md, boards/psion/code.py
- Make UK the default layout now that it is supported
- Update README
=> Psion boards update
