- .ampy
- .gitignore
- .gitmodules
- Makefile
- boards/noop.py
- upy-freeze.txt
- Lock our vendored dependencies (also pull in some new ones I will be
needing soon)
- Ensure we have a sane way of pulling those vendored dependencies into
the DFU-flashable images (upy-freeze.txt)
- Break up the Makefile into a bunch of smaller, sometimes reusable
chunks
- Try to cache some steps in the Makefile (ex. pulling submodules)
- Add a noop keyboard that simply exits, so we can flash a "keyboard"
that just dumps us straight to REPL
- Remove my personal ampy config since that's not portable at all
> Make builds a bit more robust and reusable

- .gitmodules
- Makefile
- Pipfile
- Pipfile.lock
- boards/klardotsh/twotwo_matrix_feather.py
- entrypoints/feather_nrf52832.py
- kmk/circuitpython/matrix.py
- kmk/circuitpython/util.py
- kmk/common/abstract/matrix_scanner.py
- kmk/common/event_defs.py
- kmk/common/internal_state.py
- kmk/common/keymap.py
- kmk/firmware.py
- setup.cfg
- upy-freeze.txt
This achieves the "single source of truth" model, and required some pretty heavy modifications all around. State is no longer stored in the Python classes, but in a single data store which is only modified by inbound "actions" (dictionaries). I think most of this code is reasonably self-explanatory, but holler if you run into problems.
The Pydux dependency was removed. If you run into build problems, try `git rm --cached vendor/pydux`.
This also adds a few other creature comforts, including proper logging on the device (to serial) using the standard library's logger, some board-specific enhancements for the Feather (blinks the red LED on unhandled exceptions so you know something broke), Makefile cleanup to deduplicate the mess of targets, and a change to the linter rules to allow more …
> The basic "Redux" style event loop to unify all state

- .circleci/config.yml
- setup.cfg
This will fail and block a merge on a PR if the linter fails (checks for all the normal Flake8 stuff, plus verifying that `[]{}()` literals are used instead of, say, `dict(...)`, plus verifying that all imports are sorted correctly (which can be fixed locally automatically with `pipenv run isort myfile.py`)
I'll be configuring GitHub to require the lint step for inbound PRs to be mergeable.
> Basic CircleCI setup: Lint the codebase on all inbound PRs

- kmk/micropython/pyb_hid.py
Holy shiiiiiiit that was a perf hit to check validity of keystrokes every single time.
Ripping out because on a production board, you're never going to use an invalid keycode anyway (almost certainly), and if you have something misconfigured on a dev board, you'll have REPL access to eventually see a stack trace somewhere.
> Turn this semi-automatic keyboard into a full auto

- kmk/common/consts.py
- kmk/common/keycodes.py
- kmk/entrypoints/handwire/pyboard_boot.py
- kmk/micropython/pyb_hid.py
- setup.cfg
- upy-unix-stubs/pyb/__init__.py
- user_keymaps/klardotsh/threethree_matrix_pyboard.py
What a short title for such a massive diff.
This (heavily squashed) commit adds support for Consumer keys such as
volume keys, media play/pause/stop, etc. by exposing four HID devices
over a single USB lane (as opposed to just exposing a keyboard). This
heavily refactors how HIDHelper works due to the new reporting
structure.
Many of the media keys were changed (mostly Keycodes.Media section), but
many (especially anything regarding Application keys) haven't been
touched yet - thus many keycodes may still be wrong. Probably worth
updating those soon, but I didn't get around to it yet. The definitive
list I refered to was
http://www.freebsddiary.org/APC/usb_hid_usages.php, which is basically
copy-pasta from the official USB HID spec at …
> HID: Support Consumer (media) keys

- kmk/common/abstract/matrix_scanner.py
- kmk/common/event_defs.py
- kmk/common/internal_keycodes.py
- kmk/common/internal_state.py
- kmk/firmware.py
- kmk/micropython/matrix.py
- kmk/micropython/pyb_hid.py
We're still slower than QMK, but thankfully not by a ton. Typing (ノಠ痊ಠ)ノ彡┻━┻ is now almost as fast of a process as my QMK board.
How'd I do it?
- Only send a list of pressed keys per matrix scan. This saves way more cycles than it looks like at first glance, because we used to do _several_ loops through an entire key matrix (meaning the perf hit scaled with the size of the board) to do various things: normalize it, check for any keys changed, check for which specific keys changed. We now just send a very small list of the matrix coordinates that are pressed if the length of the pressed list changes (this is assuming someone can't release key A and press key B all within the same processor tick - I'm gonna call BS if anyone claims they can do it on supported hardware). This will be far …
> Grind out as much performance as possible with lower-ish hanging fruit

- .circleci/config.yml
- Makefile
- bin/micropython.sh
- setup.cfg
- submodules.toml
We should never again have half-broken submodule clones that we can't rescue from without `rm -rf kmk_firmware` and a full re-clone, because we now copy `/vendor` to `/build` before writing anything, and detect submodule changes automatically in the Makefile.
> Improve Makefile: Stop clobbering /vendor, detect submodule changes more intelligently

- .circleci/config.yml
- .dockerignore
- .gitignore
- Dockerfile_base
- Makefile
This backports from topic-docker the base image, which we can now use in
Circle to MASSIVELY speed up our CI situation. This at least caches all the Linux-level dependencies (Python, GCC, etc. etc.) and should shave 3-5 minutes off each build stage.
It also merges the lint and test stages for simplicity's sake.
The base image can currently only be pushed by @klardotsh as nobody else
has access to the Docker Hub org, but that can change in the future.
Not finishing up `topic-docker` or #46 just yet because I need to do some Makefile foolery to ensure we are not redistributing the Nordic BLE stack within our Docker images, which I'm _pretty_ sure is a violation of their licensing terms (thus why MicroPython and CircuitPython both call out to a bash script to pull those firmware blobs at …
> Some backports from work on #46 to greatly speed up Circle builds

- kmk/abstract/hid.py
- kmk/internal_state.py
- kmk/keycodes.py
- user_keymaps/klardotsh/itsybitsy_m4_express/threethree.py
I can now press a free-floating HYPER in my keymap and see the appropriate codes in `xev` for press and release events. Cool.
> Add MEH and HYPER modifiers, refactor some cruft, and banish mostly-unused InternalState.update()

- kmk/consts.py
- kmk/firmware.py
- kmk/internal_state.py
- kmk/matrix.py
- user_keymaps/klardotsh/klarank_featherm4.py
This allows leader sequences to "time out" rather than requiring an
Enter keypress to end.
This also rolls back some unnecessary changes from #72 to the matrix
scanner for performance reasons.
In theory we can use this in the future for Tap Dance support (#40)
Resolves #1
Resolves #37
> Add LeaderMode.TIMEOUT (QMK default Leader mode)

- docs/tapdance.md
- kmk/firmware.py
- kmk/internal_state.py
- kmk/keycodes.py
- user_keymaps/klardotsh/klarank_featherm4.py
This implements the core of #40 by allowing multiple-use keys based on number of taps.
Notably lacking from this first pass:
- Changing `KC.TT` to use tap dance. For that matter, the behavior of `KC.MO` (a dependency of `KC.TT`) within a tap dance sequence is currently "undefined" at best, probably going to throw errors. For now, strongly recommend avoiding it.
- Support for more advanced tap dance configs (where keyup does different things based on how long the tap was held - for example, "tap for Home, hold for Shift")
I'll write up docs some time tonight after dinner, but I wanted to at least get this much opened up for PR so the code itself can be looked over.
> Tap Dance: Part One

- docs/keymap.md
- docs/unicode.md
- kmk/consts.py
- kmk/firmware.py
- kmk/keycodes.py
- kmk/macros/unicode.py
- user_keymaps/kdb424/klanck.py
- user_keymaps/kdb424/levinson_m4.py
- user_keymaps/klardotsh/klarank_featherm4.py
This brings this naming into consistency with both fellow consts in the
same file (ex. LeaderMode is singular) as well as the variables in which
the consts are usually used (usually a `Firmware.unicode_mode` attribute
in a keymap).
> kmk.consts: rename UnicodeModes => UnicodeMode

- kmk/boards/kitsym4_iris.py
- user_keymaps/klardotsh/kitsym4_iris.py
The thumb cluster maps a little goofy and I'd like to clean up the
keymap here - it's ENTIRELY NOT OBVIOUS how this works right now. Using
this keymap as an example, the physical layout of my thumb cluster is
actually:
Far left: Left
Next to the right: Right
Bottom right: Shift
Top right: MO(2)
You can see what this maps to in code, and it's not at all intuitive.
`swap_indicies`, which we already support, is useless here because,
unlike the Planck/Klaranck, these aren't 1:1 key swaps, but an entirely
custom mapping of columns. This will require something like QMK's
solution to fully custom (or at least partially custom) keymaps at a
core level, and isn't something I feel like tackling tonight
necessarily.
> kitsym4: Support the keeb.io Iris using the ProMicro<->ItsyBitsyM4 converter board

- kmk/firmware.py
This has been tested to HURT performance quite a lot. While animations are running, I was hitting a border of performance that I could not roll keys. With this one line change, almost all of it is solved. I recommend testing this branch before accepting, but I don't think that we still need this. If we do, than we will have to change limits as without this, performance can get very bad in some situations even with "plenty" of ram free.
> Literally hurting performance now. Needs removed

- .gitignore
- kmk/firmware.py
- kmk/matrix.py
This fixes a couple of critically-breaking issues and allows KMK to run on the newest release candidates of upstream CircuitPython. It does introduce one minor UX regression I'm willing to accept for the immediate time being.
- Resolves #104, our big breaker on alpha3 onwards, wherein the keyboard would send _nothing_ to the host until REPL was connected, and (due to a bug also resolved in this PR) would constantly re-poll this information on all `is_master` checks, thus killing the keyboard as soon as REPL was disconnected. This is generally related to https://github.com/adafruit/circuitpython/issues/1769, and the workaround mentioned by @dhalbert worked great in this context.
- Resolves a previously-unseen issue almost certainly introduced by the UART refactor somewhere around alpha5 (I …
> Compatibility with CircuitPython 4.0.0-rc2

- kmk/firmware.py
- kmk/handlers/layers.py
- kmk/handlers/stock.py
- kmk/hid.py
- kmk/internal_state.py
- kmk/key_validators.py
- kmk/keys.py
- user_keymaps/klardotsh/kitsym4_iris.py
This mostly standardizes out print statements to all look similar (they now vaguely resemble the earliest versions of KMK which used action dispatchers), which should help debugging. They also log more information, and don't need to allocate pointless dictionaries to do it.
There's slight perf improvements in here related layer activation (read: there's now one, instead of two, list objects, and it never gets recreated/reallocated, whereas there were cases where the old implementation would just toss out the old list entirely).
The rest of this is mostly menial cleanup work, touching up files I opened to investigate their perf.
> Slight perf improvements, heavily improved logging/debugging output

- Makefile
- Pipfile
- Pipfile.lock
- README.md
- kmk/boards/klarank.py
- kmk/handlers/layers.py
- kmk/handlers/modtap.py
- kmk/handlers/sequences.py
- kmk/hid.py
- kmk/internal_state.py
- kmk/key_validators.py
- kmk/keyboard_config.py
- kmk/keys.py
- kmk/led.py
- kmk/matrix.py
- kmk/rgb.py
- kmk/types.py
- kmk/util.py
- pyproject.toml
- setup.cfg
- tests/test_data/keymaps/duplicate_row_pins.py
- tests/test_data/keymaps/duplicated_pins_between_row_col.py
- tests/test_data/keymaps/ghosted_layer_mo.py
- tests/test_data/keymaps/known_good.py
- user_keymaps/kdb424/gherkin.py
- user_keymaps/kdb424/klanck.py
- user_keymaps/klardotsh/iris_r2.py
- user_keymaps/klardotsh/klarank_featherm4.py
- util/bootloader.py
- util/reset.py
I care less about what the actual style is and more that it's consistent. Black is now an official Python Software Foundation project and has mostly-sane rules. I overrode one that, [per the upstream ticket](https://github.com/psf/black/issues/594), it appears many or most major projects disagree with and also override, so I don't feel bad.
Surprisingly, we already followed Black almost to a T, and very little code was reformatted. Included is a `Makefile` target to let Black automatically fix your commit before it pushes (you could run this as a pre-commit hook in Git if you want)
> Enforce the Black autoformatter and code style

- kmk/ble.py
- kmk/hid.py
- kmk/kmk_keyboard.py
I've implemented basic BLE functionality. Before merging it should be considered that to get it to run on a Adafruit Feather nRF52840 Express I had to increase `upervisor.set_next_stack_limit(4096 + 1024)` in `boot.py` to 4096 + 4096 and compile everything to mpy files. So at least on that hardware memory limits seem to be pretty tight
> Basic BLE functionality

- kmk/matrix.py
- user_keymaps/dzervas/lab68.py
There is some `matrix` hackery to be able to pass a `DigitalInOut` instead of a pin to columns/rows. This is required as MCP23017 (IO expander) does not expose the `Pin`s.
Also I added my keymap for lab68 - the keyboard that I'm making: https://github.com/dzervas/lab68
> MCP23017 support & lab68 user keymap

- .gitignore
- kmk/ble.py
- kmk/hid.py
- kmk/kmk_keyboard.py
- user_keymaps/dzervas/lab68.py
The following can be used to change advertising BLE name:
```python
keyboard.go(hid_type=HIDModes.BLE, ble_name='Lab68')
```
Also I'm passing keyword arguments from `KMKKeyboard.go` to `KMKKeyboard.hid_helper()` to allow for various possible configurations later on (USB pid/vid, bluetooth stuff, etc.)
> [BLE] Add support to change BLE name from KMKKeyboard.go

- kmk/kmk_keyboard.py
This was completely missed for boards that do not have bluetooth. Ultimately I'd like to not import this if we don't have a reason, but guarding it would at least allow for boards that can't import to actually work on mainline kmk.
> Allows continuation of firmware if bluetooth can't be imported

- docs/rgb.md
Update to move `keyboard.pixel_pin` and `keyboard.num_pixels` into the "Configuration" table for added clarity and ease of access. These are arguably the most important configs of using RGB and should be much more up front than the bottom of the doc.
Of note, is that the editing of this file shows a weakness of Tab-based alignment. Checking the "raw" versions of items such as tables shows them to be aligned, but viewing via a text editor shows a much messier situation
Automated formatting such as the `cformat` tool I've used for QMK edits may be worth looking into.
> Update docs/rgb.md for config clarity

- kmk/keys.py
Only calling `make_key` as required can significantly reduce memory footprint on boards that don't use a lot of keycodes.
On a Feather STM32F405 Express (with the usb_hid import removed), this is the difference between being able to run and running into a memory allocation error.
Specifically:
```
import gc
print(gc.mem_free())
from kmk.keys import KC
from kmk.kmk_keyboard import KMKKeyboard
keyboard = KMKKeyboard()
keyboard.keymap = [
[
KC.A, KC.B,
KC.C, KC.D,
]
]
print(gc.mem_free())
```
will print
```
104736
59056
```
On `topic-merge-keyboard-and-state-rebased`, this prints
```
104736
Traceback (most recent call last):
File "main.py", line 4, in <module>
MemoryError: memory allocation failed, allocating 188 bytes
```
So this can save upwards of 40kB on boards that don't need all the …
> Dynamically create core key definitions as required

- docs/Getting_Started.md
- docs/config_and_keymap.md
- docs/ja/Getting_Started.md
- docs/porting_to_kmk.md
- docs/ptBR/Getting_Started.md
- docs/ptBR/config_and_keymap.md
- docs/ptBR/porting_to_kmk.md
- kmk/matrix.py
IMO the existing `DiodeOrientation` names are somewhat confusing, the names used in QMK are unambiguous and likely to be more familiar with anyone coming from QMK.
Support for the old definitions remains for compatibility, but docs have been updated to point to the more familiar naming.
> Add QMK equivalent attributes of DiodeOrientation

- docs/encoder.md
So sorry for creating another PR for Doc typos😅 . I just couldn't help it to see the Typos in the Encoder docs and the module not being imported
- Updated code to add an import and close a list element
- Add Link to Keyboard main.py
- Minor Additions to Docs and Typo fixes
> chore: Minor Fixes to Encoder Docs

- boards/atreus62/README.md
- boards/boardsource/3x4/README.md
- boards/boardsource/4x12/README.md
- boards/boardsource/5x12/README.md
- boards/boardsource/microdox/README.md
- boards/crkbd/README.md
- boards/ergo_travel/README.md
- boards/fourtypercentclub/gherkin/README.md
- boards/fourtypercentclub/luddite/README.md
- boards/keebio/iris/README.md
- boards/keebio/levinson/README.md
- boards/keebio/nyquist/README.md
- boards/lily58/README.md
- boards/reviung39/README.md
- boards/reviung41/README.md
- boards/rhymestone/README.md
- boards/tg4x/README.md
- docs/keycodes.md
- docs/rgb.md
- kmk/kmk_keyboard.py
Just noticed the word extension is misspelled on several occasions. Also the description for the two ISO-layout keys are switched
> fix doc typos and switched description for keycodes NUBS and NUHS

- kmk/handlers/stock.py
- kmk/kmk_keyboard.py
I had a problem of a layer being stuck with `MO`.
So if matrix position x has a `MO(1)` defined on layer 0 but a different key, e.g. `KC.A`, on layer 1, then the `is_pressed == True` matrix scan event will call `MO(1).on_press` and set layer 1 to be active. The `is_pressed == False` matrix scan event then will get `KC.A` from `_find_key_in_map` and call `KC.A.on_release` and there is no way to get back to layer 0.
I have changed to code to always remember the keys being pressed down and reference those same keys when the physical key is being release.
If you think about it, is there ever a case where we want to release a different keycode than was pressed?
> always release the same key as was pressed

- kmk/keys.py
I've run into the problem of running out of memory on my Adafruit ItsyBitsy nRF52840 Express with having a few hundred Key objects floating around. The empty lists for the event handlers make up about 60% of the entire Key object, it adds up quite a bit if you have many Keys defined. They are also seldom or never used, so I changed the code for the lists to only be defined when they are really needed.
> reduce Key objects memory footprint

- docs/ble_hid.md
- kmk/hid.py
- kmk/kmk_keyboard.py
To make setting the Bluetooth advertising name work as described in ble_hid.md, I have simply passed on the args from KMKKeyboard.go to the HID constructors.
> add ble_name option to KMKKeyboard.go method

- docs/Getting_Started.md
I noticed that the "here" link for the page that lists the boards in the getting start md file was incorrect (leads to 404 page.)
These changes fix it by linking to the boards dir inside of this repo.
> fix boards link in getting started

- kmk/hid.py
addresses #286.
`hid_send` was always looking at the keyboards report when figuring out the device, instead of looking at the report it's supposed to send.
Tested with USB HID, needs to be verified with BLE before merging.
> fix hid report type disambiguition

- kmk/kmk_keyboard.py
This just came up on matrix: a not fully populated keymap can crash KMK.
An index out-of-range condition should fail gracefully.
> fix: catch IndexError when looking up key in keymap

- kmk/modules/encoder.py
I tried using encoders on my keyboard, which don't have their button pins connected separable, but are part of matrix. So I initialize them with `pin_button=None`. 
When I was doing that change, I thought that encoder is not working without it, because it was spamming the serial console with: `Failed to run pre matrix function in module:  'NoneType' object has no attribute 'get_value' <EncoderHandler object at 0x20009730>`.
I now realized it was working all the time, but this change remove the errors from log.
> Remove serial log errors when declaring encoders without a button

- docs/modtap.md
- docs/modules.md
- docs/tapdance.md
- kmk/handlers/stock.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/__init__.py
- kmk/modules/holdtap.py
- kmk/modules/tapdance.py
Probably a necessary or at least helpful step to unifying multi-purpose keys (TapDance, ModTap, etc...), see #222.
It doesn't yet implement the suggested API, but it adds a new module method `Module.process_key` that allows for intercepting and potentially modifying any `Key` before it is handled by `KMKKeyboard.process_key`.
It also became apparent that the `TapDance` code/logic would need a complete rewrite, ideally something similar to `HoldTap` with a proper state machine. Current code is difficult to follow and debug.
* fixes #279
> make TapDance a module

- docs/extensions.md
- docs/lock_status.md
- kmk/extensions/lock_status.py
- kmk/modules/encoder.py
This extension exposes host-side locks like caps or num lock.
example:
```python
import digitalio
from kmk.extensions.lock_status import LockStatus
locks = LockStatus()
keyboard.extensions.append(locks)
led_clock = digitalio.DigitalInOut(board.GP25) # change to pin of LED
led_clock.direction = digitalio.Direction.OUTPUT
if locks.get_caps_lock():
led_cap_lock.value = 1
else:
led_cap_lock.value = 0
```
> implement keyboard lock status reader API

- kmk/extensions/led.py
I was getting this error while trying to run LED extension :
Starting
'module' object has no attribute 'PWMout'
Traceback (most recent call last):
File "code.py", line 67, in <module>
File "kmk/extensions/led.py", line 34, in __init__
InvalidExtensionEnvironment: Unable to create pulseio.PWMOut() instance with provided led_pin
Code done running.
This was due to using wrong module for PWMOut attribute.
> fix monocolor LED

- kmk/hid.py
- tests/keyboard_test.py
So sorry for introducing an operation breaking bug with #288 
This will hopefully fix the issue.
@xs5871 thanks for bringing it up. Could you verify, if this fixes things and whether you notice any other problems?
I currently don't have hardware set up to test properly, which is why I added the tests in the first place. And probably relied a bit too much on those
> fix bytearray.startswith not available in CircuitPython

- kmk/modules/encoder.py
Multiple encoders didn't work as a result of an unbound value of 'idx', the loop counter in the during_bootup method. Binding this value has fixed the issue. This has been tested on hardware (6 encoders) and is confirmed working.
> Fixed multiple encoders not working

- kmk/extensions/lock_status.py
The lock status extionsion is throwing exceptions on split secondaries.
Turns out you can't recieve and read HID reports if there's no HID. May need further refactoring with bi-directional split communication, once implemented.
> fix lock_status on secondary split

- kmk/kmk_keyboard.py
- kmk/modules/split.py
Potential improvement on #257, addressing #256.
Mitigates obscure ordering boundary conditions by disableing `_hid_send` entirely on a split secondary.
> disable hid_send on secondary split

- kmk/kmk_keyboard.py
- kmk/modules/encoder.py
- kmk/modules/split.py
…, as well as make it work nicely with ble.
@wildesteven I've taken your changes a bit further, and (I think) fixed some issues with the way that _is_target is decided in the split module, with help from @Tonasz. I would welcome a review, and hope I'm not stepping on too many toes.
I also added a bit more logging to kmk_keyboard to debug this, and considering that the rest of it does the same thing I think its relevant.
I don't know about using runtime.usb_connected to determine if usb is connected. The docs say that that is what it does but Tonasz said he thinks that it might be determining if the usb drive is enabled.
I also rearranged the order of the if block that decides what _is_target and split_side are, because starting an if block with a negative can be confusing to read. (was …
> Split code fix/cleanup.

- docs/led.md
- kmk/extensions/led.py
- kmk/utils.py
LED module argument `led_pin` accepts pin objects or lists of pin objects (free backwards compatibility).
Toggle, increase, and decrease are promoted to argumented keys (sadly not backwards compatible). Didn't yet figure out if we can make a `maybe_argumented_key`.
Increasing/Decreasing brightness of all LEDs doesn't reset brightness levels, but steps each LED brightness by the provided step value.
Pending:
* add `KC.LED_SET(value, *leds)` key
* documentation
usage example:
```python
rgb_ext = RGB(
led_pin = board.GP20
)
rgb_ext = RGB(
led_pin = [board.GP20, board.GP21, board.GP22]
)
LED_TOG_ALL = KC.LED_TOG()
LED_INC_0 = KC.LED_INC(0)
LED_DEC_1_2 = KC.LED_DEC(1,2)
```
> Multiple led pwm targets (see #273)

- docs/pimoroni_trackball.md
- kmk/modules/pimoroni_trackball.py
I couldn't find Pimoroni Trackball implementation so I made one. Clicking the ball acts like a left mouse button and movement translates to - depending on selected mode (`TB_MODE` keycode switches the mode on hold):
- mouse movement with light acceleration
- vertical scroll movement
Module is small and working, but there could be some remaining concerns:
1. I receive a lot of "non-lethal" errors when using it through `bitbangio` and sometimes keyboard-hanging errors when using `busio`. They occur only while moving the ball. I thought it was my fault, but @xs5871 tried my code, confirmed it worked with `busio` and AFAIK he got zero errors - we suspect I got some electrical issues on bus, which I'm not able to solve right now, but they are plausible as I had some wiring issues in the past. …
> Pimoroni trackball

- docs/modules.md
- docs/oneshot.md
- kmk/modules/holdtap.py
- kmk/modules/oneshot.py
- tests/test_hold_tap.py
Addresses #244, further generalises `HoldTap` to help unify timeout dependent function keys.
Forked from #304, will be rebased once the former is merged.
> Feature oneshot

- boards/boardsource/microdox/kb.py
- boards/crkbd/kb.py
- boards/crkbd/kb_rp2040.py
- boards/ergo_travel/kb.py
- boards/keebio/iris/kb.py
- boards/keebio/iris/kb_converter.py
- boards/klarank.py
- boards/lily58/kb.py
- boards/lunakey_pico/kb.py
- boards/reviung41/kb.py
- docs/porting_to_kmk.md
- docs/ptBR/porting_to_kmk.md
- kmk/kmk_keyboard.py
- kmk/matrix.py
- kmk/modules/split.py
- kmk/modules/tapdance.py
This replaces the current matrix scanners update object.
Instead of the implementation specific bytearray, there's a `KeyEvent` object inspired by circuitpythons version for their `keypad` library. Main difference to the current implementation is that keys are identified by a single number, instead of row and column.
Outstanding efforts to provide more/different scanners would benefit from this abstraction.
The code has been tested with a monolithic keyboard, and a split using UART. I don't expect there to be issues with BLE, but someone with a wireless split has to confirm.
The only breaking change is in the signature of `intifiy_coordinates`:
```python
intifiy_coordinates(row, column, number_of_columns)
```
I updated the only appearance of ic in the documentation, but I don't own a …
> Scanner interface rework

- docs/rgb.md
- kmk/extensions/rgb.py
Adds an optional `pixels=` parameter to the RGB extension to allow an alternate LED driver to be used. Includes documentation with example code, but no implementation (yet).
This is split out from #262 for simplicity's sake. The Pimoroni boards will be in a future PR once these changes land, as they depend on both this PR and #329.
> Override LED creation in the RGB extension.

- boards/kyria/README.md
- boards/kyria/kyria_v1_kb2040.py
- boards/kyria/kyria_v1_rp2040.py
- boards/kyria/main.py
Commit adds Kyria board configuration and examples for RP2040 boards with Pro Micro layout.
Thank you **nonuke** for making and testing the KB2040 pinout.
`coord_mapping` based on current master, so it might need an update if it changes till the merge
> Add Kyria board configuration and examples

- docs/scanners.md
- kmk/kmk_keyboard.py
- kmk/matrix.py
- kmk/scanners/__init__.py
- kmk/scanners/native_keypad_scanner.py
- Introduce Scanner base class for MatrixScanner
- Create new Scanner using built-in keypad module
- Allow overriding the scanner used by KMKKeyboard
This is split out from #262 for simplicity's sake. The RGB changes and the Pimoroni boards will be in separate PRs.
> Custom matrix scanners

- boards/boardsource/microdox/kb.py
- boards/crkbd/kb.py
- boards/crkbd/kb_rp2040.py
- boards/ergo_travel/kb.py
- boards/keebio/iris/kb.py
- boards/keebio/iris/kb_converter.py
- boards/lily58/kb.py
- boards/lunakey_pico/kb.py
- kmk/modules/split.py
`Split.split_flip` stopped working after reordering of `_init_matrix` and `during_bootup` in #312.
> Fix split flip

- boards/pimoroni/README.md
- boards/pimoroni/keybow/code.py
- boards/pimoroni/keybow/keybow.py
- boards/pimoroni/keybow_2040/code.py
- boards/pimoroni/keybow_2040/keybow_2040.py
- docs/scanners.md
- kmk/kmk_keyboard.py
- kmk/scanners/__init__.py
- kmk/scanners/native_keypad_scanner.py
Two new boards, along with some minor changes to the matrix injection code to reduce boilerplate.
Things to note:
- Both boards use the new keypad.Keys scanner
- The keymaps are *very* barebones, I've gone for proof of functionality for now.
- RGB LEDs on the keybow (APA102) work, but the keybow2040's IS31FL3731 controller needs more work.
- The keybow works great with an nrf52840 via the adaptor linked in the code, but the original raspberry pi hardware has permanently stuck keys. Either the mapping is wrong or there's something weird about the port which I still need to look into.
> Adding Pimoroni Keybow and Keybow 2040

- boards/pimoroni/keybow_2040/code.py
- boards/pimoroni/keybow_2040/is31fl3731_pixelbuf.py
- boards/pimoroni/keybow_2040/keybow_2040.py
The IS31FL3731 that the Keybow2040 uses is actually a fairly complex beast - it can even do basic video stuff on a bunch of LEDs!
Since the adafruit driver for it has a bunch of implementation-specific stuff, using this for the keybow2040 isn't necessarily going to be directly comparable to using it in any other case so I left the wrapper class in the board directory rather than putting it somewhere shared.
Turning this into a more generic wrapper that we can use with any RGB driver is pretty trivial, to the point where it's almost not worth doing. It'll really only end up reducing the number of copied lines for by 4-5 for most cases anyway.
> Fixed IS31FL3731 LEDs on keybow 2040

- docs/sequences.md
Quick update to Sequences.md documentation to demonstrate `simple_key_sequence` which is otherwise undocumented without searching through user keymaps.
> Add example of simple_key_sequence

- kmk/kmk_keyboard.py
- kmk/scanners/native_keypad_scanner.py
keypad needs diode direction as name argument, and debug output wasn't conditional.
> fix keypad matrix init and unguarded debug print.

- kmk/modules/layers.py
KC.MT(), typing the specified key would occasionally stop with the following error
```
ファイル "main.py", 行 86, in <module>
ファイル "/lib/kmk/kmk_keyboard.py", 行 408, in go
ファイル "/lib/kmk/kmk_keyboard.py", 行 458, in _main_loop
ファイル "/lib/kmk/kmk_keyboard.py", 行 115, in _handle_matrix_report
ファイル "/lib/kmk/kmk_keyboard.py", 行 181, in _on_matrix_changed
ファイル "/lib/kmk/kmk_keyboard.py", 行 189, in process_key
ファイル "/lib/kmk/keys.py", 行 429, in on_release
ファイル "/lib/kmk/modules/layers.py", 行 21, in curried
ファイル "/lib/kmk/modules/holdtap.py", 行 113, in ht_released
ファイル "/lib/kmk/modules/layers.py", 行 82, in send_key_buffer
TypeError: function takes 2 positional arguments but 4 were given
```
As the error message says, it seems that there are too many arguments to call `_find_key_in_map`.
> Fix _find_key_in_map callings

- kmk/extensions/rgb.py
relates to #224. Implements:
- use common clamping function in incrementing/decrementing methods
- faster HSV to RGB conversion
- make neopixel lib only necessery for default pixelbuffer
HSV domain has been changed from [0-360, 0-100, 0-100] to [0-255, 0-255, 0-255]. Makes the math easier and faster for 16 bit fixed point calculations.
> Enhancement rgb

- kmk/kmk_keyboard.py
- kmk/kmktime.py
- stricter timeouts: Instead of adding an entire millisecond, use a list
of timeouts that are supposed to be handled on the same tick. This
reduces the delay between target tick and actual tick, especially for
many timeouts issued to the same tick, i.e. combos.
- consistent timeouts: Timeouts are now guaranteed to be handled in the
order they were issued. Timer rollover is handled properly.
caveat / change to the interface: the returned `timeout_key` is a tuple
of the target timeout tick and the index of the timeout at that tick.
> implement stricter and more consistent timeouts.

- Makefile
It's not unlikely to have multiple mpy-cross binaries on a system, so it makes sense to let user choose one.
Customizable MPY_SOURCES let me compile board specific files or external libraries as well.
> Allow passing user-defined MPY_SOURCES and MPY_CROSS to make

- kmk/keys.py
Resolves #369:
This removes multiple layers of indirection, effectively making
`make_shifted_key` only as heavy on the stack as the reguler `make_key`.
> fix pystack exhaustion caused by make_shifted_key.

- kmk/handlers/sequences.py
WinCompose requires the `enter` key to be typed at the end of a special unicode character. In order to help print emojis and emoticons in a windows environment, I have added the enter key to the Windows compose unicode sequence method. I have tested this with my local keyboard.
> Fix WinCompose usage

- docs/encoder.md
I had to dig through the code to find out what to do... adding it to the docs...
> add `None` to account for no encoder button in encoder docs

- boards/pimoroni/keybow/keybow.py
- boards/pimoroni/keybow_2040/keybow_2040.py
- docs/scanners.md
- kmk/kmk_keyboard.py
- kmk/scanners/keypad.py
Exposes all options of the CP `keypad` modules through our scanner wrapper.
Depends on #388; ready for review once dependency is merged.
> Enhancement scanner options

- kmk/keys.py
Additional aliases for macOS key names to match QMK behavior.
> Add ROPT and LOPT as alias for alt keys

- docs/scanners.md
- kmk/kmk_keyboard.py
- kmk/modules/split.py
- kmk/scanners/__init__.py
- kmk/scanners/digitalio.py
- kmk/scanners/keypad.py
Support for multiple (i.e. a list of) scanners.
`KMKKeyboard.matrix` can either be a single scanner (support for current implementations), or a list of scanners.
`coord_mapping` for mirrored non-square matrices or multiple scanners has to be defined manually -- there's no general solution. Individual scanner "flips" may be added in the future.
Before merging, confirmation from a split user would be appreciated.
> Enhancement: multiple scanners

- docs/oneshot.md
This adds an explanation, a short example and a longer block of code that contains everything needed to allow for all (left) modifier combinations.
> Updated OneShot doc with example OneShot Modifier Combination

- kmk/modules/split.py
Resolves #406.
There where two independent bugs in the split module: one introduced recently by #400, and one that's a month old by #366.
The older PR claims to fix something, but doesn't say what, and completely disables communication from target to initiator. If anyone finds that my fix is a regression, please enlighten me.
(ps: tested with hardware UART)
> fixes scanner init and bi-directional communication in split module

- kmk/keys.py
- tests/test_kmk_keys.py
- Add tests for ModifierKey chaining
- Rewrite ModifierKey.__call__ for correctness and readability
- __call__ now maintains handlers and meta, like clone()
> refactor Key and ModifierKey __call__ methods

- docs/encoder.md
- docs/scanners.md
As you may have seen I have closed my last split/encoder pr. After talking with xs and being made aware that the encoder scanner does what I wanted (splits with encoders). So I figured out what I needed to do to get it working and now have updated the docs to be what would have been nice to have and would have made it effortless for me. 
Also made changes to lines 29 and 30 because they are just wrong and would not work.
>  Added on to the docs for splits using encoders

- docs/keys.md
- kmk/keys.py
- tests/test_kmk_keys.py
Rework of #405.
This is the minimum that gives KC.keyname, KC['keyname'] and KC.get('keyname') with tests.
> Minimum necessary to add index and get capability and tests

- kmk/modules/combos.py
- tests/test_combos.py
There is a bug where buffered keys weren't re-evaluated after a layer change.
I'll consolidate the key buffer code from combos and holdtap in the near future.
> fix combo buffer replay /w layer-switch

- docs/tapdance.md
- kmk/key_validators.py
- kmk/modules/holdtap.py
- kmk/modules/layers.py
- kmk/modules/modtap.py
- kmk/modules/oneshot.py
- kmk/modules/tapdance.py
- kmk/types.py
Refactors the `tapdance` module on top of `holdtap`.
This looks like a bigger "change" than it is. There's some plumbing rework in every module that builds on `holdtap` but no functionality has been changed.
Tap dances allow any kind of `holdtap` based key and propagates / adheres to the specific attributes of each key in the sequence -- for example:
```python
KC.TD = (KC.A, KC.MT(B, KC.LALT, prefer_hold=False), KC.TT(1, tap_time=3000), tap_time=200)
```
does what you'd expect it to do, without the need for `tapdance` to resolve an action, before the `holdtap` action starts.
For consistency any non-`holdtap` key gets replaced by `holdtap` with identical hold and tap. That is also the only major change to the layer module: `KC.LT` and `KC.TT` are composed of a tap and a hold key, instead …
> Refactor tapdance

- boards/anavi/knobs3/README.md
- boards/anavi/knobs3/anaviknob.py
- boards/anavi/knobs3/code.py
Add support for ANAVI Knobs 3: an open source programmable mini
mechanical keyboard with 3 rotary encoders and Seeed XIAO RP2040.
This is open source hardware designed with KiCad.
> anavi/knobs3: Add ANAVI Knobs 3

- boards/anavi/knobs3/code.py
Enable RGB/Underglow/NeoPixel for the built-in NEOPIXEL LED on
Seeed XIAO RP2040. By default set it 25% brightness with rainbow
animation.
> boards/anavi/knobs3/code.py: Enable RGB

- docs/peg_oled_display.md
- kmk/extensions/peg_oledDisplay.py
- kmk/extensions/peg_oled_display.py
Hello, another pr on the docket for you lol. This is my oled extension, I have been spending a lot of time on this and I don't think I need to make any more changes in the near future so it's time to let others play with it. 
you will see that it's prefixed with Peg. Peg is some software I am working on to let you configure your kmk board. The prefix is to denote that this is the OLED extension that peg interacts with. Anyone can use it and make changes to it but if there were 2 OLED extensions I wanted people to know that they are different. This does not seem to be a problem the last OLED extension never got pulled in. Being that not only users will interact with this but also other code some of my design decisions were about that. I have however tried to make this easy to use for the …
>  added oleds 

- docs/peg_rgb_matrix.md
- kmk/extensions/peg_rgb_matrix.py
you will see that it's prefixed with Peg. Peg is some software I am working on to let you configure your kmk board. The prefix is to denote that this is the RGB extension that peg interacts with. Anyone can use it and make changes to it but there are two RGB extensions now (this one is very different) but still. Being that not only users will interact with this but also other code some of my design decisions were about that. I have however tried to make this easy to use for the end-user.
The primary change is that here we map each index in your led chain to its equivalent key, eg if `KC.Q` is the second key in your keymap array the second color is your `ledDisplay` will light up "Q". Beyond that mine is just less feature full lol, no animations as I have not had time for them yet and want …
> Peg rgb matrix

- kmk/kmk_keyboard.py
We discovered a crash when keys are mashed (see #424). This crash is unrelated to the original issue, but should still be mitigated. It occurs when keys are pressed _very_ fast and some key press events are dropped, but matching key releases are propagated.
It would be nice to fix this at a lower level, but I assume this already happens in the scanner from CP and thus out of our immediate influence.
> fix crash on releasing dropped key presses

- docs/split_keyboards.md
This change fixes a couple of typos in the import statements for the split keyboard code examples.
> Correct import statements in example code

- docs/Getting_Started.md
- kmk/extensions/peg_rgb_matrix.py
Rgb matrix code can now use the drive name to work out if it is on the right or left side of the keyboard.
You can still pass the bool if you want but it will use the drive name as default.
Also getting started was just a lie.
> RGB matrix split side using drive name

- boards/anavi/knobs1/README.md
- boards/anavi/knobs1/anaviknob.py
- boards/anavi/knobs1/code.py
Add support for ANAVI Knob 1: an open source programmable mini
mechanical keyboard with a rotary encoders and Seeed XIAO RP2040.
This is open source hardware designed with KiCad, the smaller
version of ANAVI Knobs 3.
> anavi/knobs3: Add ANAVI Knob 1

- docs/combos.md
- kmk/modules/combos.py
- tests/test_combos.py
Implements enhancements mentioned in #409 and #427:
- more flexible combo reset handling: enables modmorph / key override functionality. Hold down a chord -> activate combo -> release and tap one of the chord keys -> repeat combo without having to tap the entire chord.
- faster combo activation: if there's only one combo left and matching, activate it without waiting for a timeout.
This took a lot longer to get right than it should. Turns out my initial design with dynamically changing match/reset lists is getting unmaintainable. Thought the matching could be faster with a map-reduce like approach, but let's be realistic: few people will have so many combos that reallocating them constantly into different lists is a better solution than iterating over all and checking a flag.
Will port …
> Enhancement combos

- docs/keycodes.md
- docs/sequences.md
* updated [keycodes.md](docs/keycodes.md) to reflect KC.MACRO_SLEEP_MS documentation within [sequences.md](docs/sequences.md) rather than "macros"
* provided an example of usage within the sequences documentation
> Updated KC.MACRO_SLEEP_MS(ms) documentation

- kmk/extensions/rgb.py
The code was wrongly iterating the neopixel, running `fill()` on every
individual pixels.
I suggested the change that was sucessfully tested by @ziptyze on discord.
> [rgb] fix set_rgb_fill method

- kmk/keys.py
When making a typo in a key in the keymap, this allow to know where to look precisely.
> add info to InvalidKey exception

- kmk/modules/holdtap.py
- tests/test_hold_tap.py
May resolve #466.
Refactors some of the `HoldTap` code that caused unaccounted-for side-effects when more than one ht is active at once + more unit-tests.
In draft until verified by the issues OP.
> fix inconsistencies with chained holdtap keys

- kmk/extensions/led.py
- kmk/extensions/lock_status.py
- kmk/extensions/peg_rgb_matrix.py
- kmk/extensions/statusled.py
- kmk/hid.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/pimoroni_trackball.py
- kmk/scanners/digitalio.py
little tweak in the debug output to make things more readable:
- wrap KMKKeyboard report to 100 char (changeable), not splitting a key=value
- include a \n before MatrixChange as those are the begining of  a new logical 'block'
example result:
```
MatrixChange(ic=14, pressed=True)
KeyResolution(key=Key(code=1021, has_modifiers=None))
KMKKeyboard(
debug_enabled=True, diode_orientation=1, matrix=(<MatrixScanner object at 0x2000eef0>,),
unicode_mode=0, _hid_helper=USBHID(REPORT_BYTES=9), keys_pressed=set(),
_coordkeys_pressed={14: Key(code=1021, has_modifiers=None)}, hid_pending=False,
active_layers=[1, 0], _timeouts={},
)
MatrixChange(ic=52, pressed=True)
KeyResolution(key=Key(code=20, has_modifiers={1}))
KMKKeyboard(
debug_enabled=True, diode_orientation=1, matrix=(<MatrixScanner object at …
```
> [debug] improve debug readability

- kmk/modules/encoder.py
`GPIOEncoder` needs 4 arguments, the last one being encoder direction. Unfortunately, seems like `EncoderHandler` limits the number of arguments to 3, so the inverted direction never gets passed and always defaults to `False`. 
I fixed this by removing the argument number limit entirely. This makes it in line with I2C encoder that doesn't have a limit. The limit also may cause confusion in the future as no additional arguments will be accepted either in case the encoder method will need to be extended (that happened to me, that's how I discovered this issue in the first place).
Test code from `main.py`:
```
encoder_handler.pins = ( (board.GP14, board.GP15, None, True), )
encoder_handler.map = ( ((KC.N1, KC.N2, KC.NO), ), )
```
Setting True to False and vice versa didn't have an effect …
> Fix encoder direction inversion being ignored

- docs/rgb.md
The link is hardcoded to a commit from 2018-12-21 (version 3.3.5) while
we are currently at 6.3.3.
The rgb makes use of the fact that NeoPixel is a subclass of PixelBuf
but that was not true back then. Hence some people following the link in
the doc get a neopixel library incompatible with kmk.
> [doc:rgb] fix link to neopixel lib

- docs/rapidfire.md
- kmk/modules/rapidfire.py
Implements a module that lets users hold a key to repeatedly send a tap.
> Add RapidFire module

- kmk/keys.py
- tests/test_kmk_keys.py
The key names for `BLE_REFRESH` was a string instead of a tuple. That matched `KC['_']` and threw an error.
I put a unit test for underscore in, probably overkill, but shouldn't do any harm.
> fix KC["_"] resolving to BLE_REFRESH

- README.md
- docs/Getting_Started.md
As per the conversation in #205, I've specified 7.0 as the explicit minimum version for KMK in preparation for static typing and made the requirement more apparent by placing it on the main readme.
> Explicitly define CircuitPython 7.0 or higher as the minimum supported version

- kmk/keys.py
- kmk/modules/combos.py
- tests/keyboard_test.py
- tests/test_hold_tap.py
Pretty much a complete refactor of the keyboard emulation unittest + fixes to get everything working again.
Current version was impossible to read, had terrible debug output, and most importantly didn't do bjective comparisons of generated and desired keycode reports.
KC has an `__iter__` now, so we can do reverse lookups.
> Fix unittest

- boards/keebio/iris/kb.py
I hit the ever-feared factory reset (internal storage wipe) bug of NiceNanos on my Keebio Iris R2 (yes, the socketed ones that went out of production years ago - I built one in 2018 and the other in 2019 some time on the old PCBs) and had to set KMK up from scratch. This PR is the first of two bits of learning from that (unpleasant) experience: that somehow the Iris kb.py (I can't type backticks, GESC must be broken... make that three things) was almost entirely off by one on coord map indicies on the right half, so I couldn't even hit enter.
This allows me to hit enter, and indeed, all other keys (including some on the left half that were wrong).
> fix(irisr2/nicenano): fix grossly incorrect coordinate mapping

- docs/keycodes.md
- kmk/handlers/stock.py
- kmk/keys.py
Adds `KC.RELOAD` for software reload which makes use of [`supervisor.reload()`](https://docs.circuitpython.org/en/latest/shared-bindings/supervisor/index.html#supervisor.reload). This differs from the current `KC.RESET` because it only reloads the software, preserving any active serial connections and doesn't clear things like tracebacks. Useful for anyone that [turns off auto-reloading](https://docs.circuitpython.org/en/latest/shared-bindings/supervisor/index.html#supervisor.disable_autoreload).
> Add keycode for software reload

- kmk/keys.py
The KMK documentation lists keycode name `BSPACE` as a valid name for the backspace key: http://kmkfw.io/docs/keycodes#basic-keys
However, using `KC.BSPACE` in one's keymap throws the following error:
```
ValueError: Invalid key: BSPACE
```
To resolve this issue, this PR simply adds `BSPACE` as a valid alias for the backspace key.
> Add 'BSPACE' keycode for backspace

- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/layers.py
- kmk/utils.py
A "universal" debug interface that:
- can be used from anywhere in the code base (no access to `KMKKeyboard.debug_enabled` required)
- shows where the message is coming from (named debug instances)
- has timestamps... I'm amazed we had to go without one for so long
- could easily be extended to optionally show other metrics, like stack size or differential memory at ever message
Originally I planned to have the is-debug-enabled-check also in the debug class. Then I noticed that we have f-strings everywhere now, and those would be evaluated before the check happens, wasting precious CPU cycles.
I quite like the syntax of f-strings, but is it worth keeping and carrying an `if debug.enabled:` through the code?
> implement global debug interface.

- kmk/modules/combos.py
- tests/test_combos.py
Fix for #528. 
Resets combos on key-up if there isn't a current match.
Added 4 new tests for this case, too, with different delays in key press/release and checking that it works whether the other key is a combo key or "inert".
I also added some type hints to help me with debugging and left them in, hope that's alright since it'll need to be done anyway for #205.
> Fix key pressed before combo making combo wait for timeout

- boards/anavi/macro-pad-10/README.md
- boards/anavi/macro-pad-10/code.py
Add support for ANAVI Macro Pad 10. This is an open source, programmable mechanical keyboard with 9 hot-swappable mechanical switches, RGB WS2812B underlighting and yellow backlit a rotary encoder and [Seeed XIAO RP2040](https://www.seeedstudio.com/XIAO-RP2040-v1-0-p-5026.html).
ANAVI Macro Pad 10 has been designed with the cross platform and open source electronics design automation suite KiCad. All KiCad [files and schematics are available at GitHub](https://github.com/anavitechnology/anavi-macro-pad-10) under [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)](https://creativecommons.org/licenses/by-sa/4.0/).
Best regards,
Leon
> anavi/macro-pad-10: Add ANAVI Macro Pad 10

- kmk/modules/pimoroni_trackball.py
The pimoroni trackball module "force reset" pointing HID reports to zero if nothing was happening.
That interferes with other modules interfacing with the pointing HID.
> fix trackball module forcing reports to zero

- docs/Getting_Started.md
- docs/ja/Getting_Started.md
- docs/ptBR/Getting_Started.md
- docs/ptBR/support.md
- docs/support.md
- kmk/consts.py
- kmk/kmk_keyboard.py
resolves #544, reclaiming invaluable low-double-digits of bytes.
I didn't purge the fingerprint generation for mpy-cross builds from the Makefile, because that could actually be usefull.
Translations are courtesy of google translate.
> remove reference to disfunct KMK_RELEASE.

- kmk/hid.py
When the usb connection is lost (for example when plugged into a pc that
keep the usb powered when shut down) the kb is lost and need to be
unpluged to be rebooted.
My guess is that the failling `hid_report.send()` change some internal
state that could not recover by itself.
This prevent even trying to send the report when the usb is not
connected. This fix has been tested working on me and another discord
user so far. The result seems consistent even if the test period has not
been very long yet.
> [usb] Allow kb to lost usb connection without getting lost

- boards/lunakey_pico/main.py
It is necessary to load the media keys extension to use the media keys (KC.VOLD, KC.VOLU and so on). However, the current file for Lunakey Pico does not do that. This pull request adds the logic to register the extension for the Lunakey Pico keyboard.
> Fix the issue of Lunakey Pico regarding the media keys extension loading

- boards/anavi/macro-pad-10/code.py
Set diode orientation to COL2ROW as per the latest hardware
revision of ANAVI Macro Pad 10.
Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
> boards/anavi/macro-pad-10: Set to COL2ROW

- kmk/kmk_keyboard.py
- kmk/modules/combos.py
- kmk/modules/holdtap.py
- kmk/modules/layers.py
This is an approach to make modules with side effects more consistent (related to #495).
At the moment, I think only hold-tap (and it's decendents) and combos profit. Modified keys can be re-inserted into the `process_key` pipeline after the module that modified them, basically "picking up where they left of". It's not a super clean, automatic thing for all modules (yet), I acknowledge that; but it's a simple enough solution, doesn't break unit-tests or changes too much of the core firmware.
Input from contributors of #495 is of course welcome, especially towards perceived effectivenes.
> add continue-with-module-nr-idx to key processing

- docs/README.md
- docs/modules.md
- docs/serialace.md
- kmk/modules/serialace.py
Every application needs a gaping hole in security, ready to be exploited.
I don't even remember how I got the idea, but in the past people were asking questions like "*how can I tell my keyboard `x` from my host OS*".
Well, here's an API that allows arbitrary code execution over the built-in data serial (which is different from the REPL/console).
This is as much a proof-of-concept as it is probably a terrible idea.
How to use:
1. enable the data serial in `boot.py`:
```python
import usb_cdc
usb_cdc.enable(data=True)
```
2. load module (obvious)
3. assuming serial on `/dev/ttyACM1` and _explicitly_ set to send `\n` as line break (this is not always the default):
```bash
$ echo "keyboard.active_layers" > /dev/ttyACM1
$ cat /dev/ttyACM1
[0]
$ echo "exec('from kmk.keys import KC; …
```
> implement arbitrary code execution (ACE) over data serial.

- kmk/modules/holdtap.py
- kmk/modules/modtap.py
- kmk/modules/tapdance.py
resolves #566.
This was a bit more involved than anticipated. The "problem" is, that the hold-tap logic isn't using the pre-processing pipeline to convert hold-tap keys to regular keys. Hold-tap keys are more or less handled as dead keys that tap the resulting hold/tap key, instead of "converting" the hold-tap key into the respective result. It's an algorithmical nuance and I'm not sure atm which implementation would be more resource efficient, considering a trade-off between speed and memory consumption.
> fix stack exhaustion for certain hold-tap actions

- docs/cg_swap.md
update doc typo so that import will now correctly point to the `modules` directory rather than the non-existent `module` directory
> fix import typo in cg_swap.md

- .gitignore
These used to be ignored, and need to be added back.
> dstore gitignore

- kmk/extensions/rgb.py
addresses #559.
Doesn't fix the discrepancy in the documentation.
> make rgb.val_limit apply globally

- docs/combos.md
- kmk/modules/combos.py
Added an option to use key coord in the matrix to make combos. this allows to press / release combos regardless of layer and Key.
> Add key coord combos - Replaces #587

- docs/sequences.md
Helped a user create this macro, and thought this may help others with the same issue. `no_press' and 'no_release' are used in the sequences source, but not documented well here, so this seemed like a good inclusion.
> sequences update with new example

- kmk/extensions/rgb.py
Prints class and length of the chosen pixelbuffer to debug.
> add debug info for pixelbuffer to RGB extension

- docs/modtap.md
- kmk/modules/holdtap.py
- tests/test_hold_tap.py
Continuation of #479.
Resolves #593.
* repeat is reset after `tap_time`
* repeat works for both tap/hold keycode
* fixed `KC.HT` getting over-written by modules that inherit from and are loaded after HoldTap.
> Feature holdtap repeat

- docs/boot.md
This should auto detect better and cause less people that copy paste to get a board in a softlock state.
> Boot.py docs better example

- kmk/kmk_keyboard.py
- kmk/modules/combos.py
- kmk/modules/holdtap.py
- kmk/modules/layers.py
- kmk/modules/oneshot.py
- kmk/modules/tapdance.py
- tests/keyboard_test.py
- tests/test_hold_tap.py
- tests/test_tapdance.py
resolves: #585
Instead of handling resumed key events in a deep stack, buffer them until the next main loop iteration. New resume events that may be emitted during handling of old resumes are prepended to that buffer, i.e. take precedence over events that happen deeper into the buffer/event stack. Logical replay order is thus preserved.
This obviously constitutes an architectural change to the way we handle buffered or deferred key events and is open for debate.
In my opinion it's cleaner and easier to debug than handling key events from wherever and whenever in the code, especially from within anonymous timeout callbacks. No more `keyboard._send_hid()` littered throughout modules. No more multiple key events during processing timeouts. One API to rule them all! (ok, well, almost)
> fix pystack exhaust during resume_process_key.

- kmk/modules/modtap.py
- tests/test_hold_tap.py
Adds a unittest for the "holdtap repeat" feature.
And to make the test pass and deduplicate code: replaces the modtap validator its parent's (as suggested in #616).
> Enhancement holdtap repeat unittest

- docs/en/keycodes.md
resolves #631
We can't do `KC.LT`, because it collides with layer tap; ergo also remove `KC.GT`.
> remove not-implemented keycodes from docs

- README.md
As the branch name suggests, this started as somewhat of a formal farewell and thanks to the original co-author and four-years-running co-maintainer of KMK, @kdb424, who has relayed to us that he would like to step down from the project effective immediately. I was going to add somewhat of a `Maintainers Emeritus` subheading as a thanks, but instead will just propose removing the entire "team" blurb from the README: it doesn't serve too many useful purposes that the Git log cannot at this point anyway.
Thanks, kdb. I'm sure we'll build some more silly toy projects together soon. Four years almost to the day from starting this project is about time we kick around some new wild idea anyway, yeah? :)
> readme: remove authorship and maintainer list blurb

- kmk/modules/capsword.py
- tests/test_capsword.py
Before, the allowed alphabet of characters for CapsWords was exclusive of the letter Z, and the allowed number set was exclusive of the number 0.
Now, those characters are included, so using them won't interrupt CapsWords.
> fix: Include Z and 0 in CapsWords ranges

- README.md
Resolves #437 by linking the Zulip chat as the official asynchronous discussion and support platform.
Refs #650 by demoting and discouraging the Discord and Matrix links, both to be decommissioned at some future time as discussed in the issue thread.
> docs: Replace Discord and Matrix links with Zulip in README.

- docs/en/pimoroni_trackball.md
Added how to set the rotation angle of the pimoroni trackball breakout to the existing example in the docs. 
It took me a while to find out, so I thought this information could be useful for others as well.
> add trackball rotation to example in docs

- docs/en/oneshot.md
The Chord example references OS_LCTL_LSFT which is not set in the code above it.
> OS_LCTL_LSFT should be set in example code

- boards/anavi/anavi-arrows/README.md
- boards/anavi/anavi-arrows/arrows.py
- boards/anavi/anavi-arrows/code.py
Add support for ANAVI Arrows: an open source programmable mini hot-swappable mechanical keyboard with 4 keys, a rotary encoder, mini OLED I2C yellow-blue display and Seeed XIAO RP2040. This is an open source hardware device designed with KiCad.
> anavi-arrows: Add ANAVI Arrows

- docs/en/quickpin.md
The image `'pro_micro_pinout.png'` in the `quickpin.md` docs was linking to here: 
https://github.com/KMKfw/kmk_firmware/blob/master/docs/en/img/pro_micro_pinout.png - which does not exist.
Now it gets correctly linked to: 
https://github.com/KMKfw/kmk_firmware/blob/master/docs/img/pro_micro_pinout.png
> Fixed image link in quickpin.md docs

- boards/anavi/macro-pad-12/README.md
- boards/anavi/macro-pad-12/code.py
Add support for ANAVI Macro Pad 12: an open source programmable small hot-swappable mechanical keyboard with 12 keys, mini OLED I2C display and Seeed XIAO RP2040. This is an open source hardware designed with KiCad.
> anavi/macro-pad-12: Add ANAVI Macro Pad 12

- boot.py
- docs/en/flashing.md
That awful hack is finally no longer necessary.
obsoletes #656
resolves #655
> Remove supervisor stack limit from boot.py

- docs/en/extension_stringy_keymaps.md
Following this issue: 
https://github.com/KMKfw/kmk_firmware/issues/669
[Zulip Chat Topic](https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/Do.20layers.20MO.281.29.20work.20in.20StringyKeymaps.3F)
I felt the need to update the [Stringy Keymaps documentation](http://kmkfw.io/docs/extension_stringy_keymaps/).
In it's current form the documentation does not mention that it's possible to mix and match string-based key references and standard keycodes.
I added an example showcasing this.
___
The sentence
> Enables referring to keys by 'NAME' rather than KC.NAME.
may lead users to incorrectly assume it applies to layer keycodes like `KC.MO(layer)`, resulting in confusion as it needs to still be referenced using the notation of e.g. `KC.MO(1)` rather than `MO(1)`.
I also added a …
> Added more examples to the Stringy Keymaps documentation

- kmk/hid.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/adns9800.py
- kmk/modules/easypoint.py
- kmk/modules/layers.py
- kmk/modules/mouse_keys.py
- kmk/modules/pimoroni_trackball.py
We're currently handling pointing device HIDs completely independent and agnostic of one another.
That requires duplicate code and when using more than one PD HID module, they interfere with each other.
This is an attempt to consolidate and build a central API for axis movement.
Mouse keys can be handled just like keyboard and consumer control keys. Unfortunately that doesn't work with axes, because they have continuous states (the amount of movement), not binary (pressed/released). I'm still undecided about the exact implementation details and open to suggestions.
> Enhancement global pointing device

- boards/anavi/knob1/code.py
- boards/anavi/knobs3/code.py
- boards/anavi/macro-pad-10/code.py
With the divisor set to two the encoders work much smoother on the Anavi Knobs 1 and 3 and the MacroPad10.
> Set encoder resolution on Anavi boards

- setup.cfg
Apply the the same linter format exceptions to `kb.py` as for `main.py`.
> Add linter format exception for `kb.py`

- kmk/keys.py
I propose to remove the extra ".__iter__()" in KeyAttrDict iterator: iterating elements in the partition already implicitly calls its __iter__ method.
Actually when I use the dictionary iterator with this extra call, it triggers an error since an iterator does not have an iterator. This is now no longer the case.
For the story, I had to use this iterator to copy the dictionary and stumbled upon this issue.
Most likely this iterator is not being used in current code (or if it is, how could it be working?).
> Removed erroneous extra ".__iter__()" in KeyAttrDict iterator

- kmk/modules/oneshot.py
- tests/keyboard_test.py
- tests/test_hold_tap.py
- tests/test_oneshot.py
resolves #427
resolves #535
Oneshot keys automatically stack and reset timeouts. I'm not going to implement an option to toggle that off, unless there's a real world application / request.
> Feature oneshot stacking

- kmk/keys.py
- kmk/modules/holdtap.py
- kmk/modules/string_substitution.py
- tests/test_kmk_keys.py
Don't crash the firmware just because there's a typo or key from an unused module in the keymap.
part of #719
> Resolve invalid keys to KC.NO instead of ValueError

- kmk/kmk_keyboard.py
Implements the backend logic to allow using `during_bootup` as a validation or self-check mechanism, and safely ignore any modules/extensions which fail that check.
part of #719
> Remove modules and extension that fail during_bootup

- kmk/extensions/rgb.py
Finishes #719
Moving the neopixel init mitigates keyboard crashes if the library is missing, or hardware can't be initialized.
That is something we should consider doing for other modules and extensions as well.
> Move neopixel initialization into during_bootup

- kmk/extensions/__init__.py
- kmk/extensions/rgb.py
- kmk/kmk_keyboard.py
- kmk/modules/__init__.py
Adds a `deinit` method that gets called when `keyboard.go()` terminates. Allows to implement cleanup, like hardware deinit, or writing persistant state to flash.
> Add deinit method to modules and extensions

- kmk/kmk_keyboard.py
- kmk/modules/holdtap.py
- kmk/modules/oneshot.py
- kmk/modules/tapdance.py
- tests/test_holdtap.py
- tests/test_layers.py
resolves #739 and adds unit test for that scenario.
> Fix layer tap interrupted

- kmk/utils.py
This is one of this stupid "lets see what happens" hacks that turn out to be unexpectedly effective.
Makes debug messages so much faster (~1ms instead of ~4ms), reduces static memory consumption by ~100k, and even reduces dynamic memory consumption because there's no re-formatting-string-allocation going on.
There's an argument to be had about removing f-strings where possible and replacing them with staticly formatted equivalents.
> Speed up and reduce memory footprint of debug template

- kmk/kmk_keyboard.py
- kmk/utils.py
* Declutter and denoise the debug output in general.
* Avoid f-strings. They're nice to look at, but use a lot of ROM, RAM, and time during formatting.
* Remove all "debug" information from `KMKKeyboard.__repr__`. It's printed out once at init and the info it gave was useless at that point. Even more free memory.
* Add a memory footprint debug info after initialization.
> Denoise core debugging and improve improve performance.

- kmk/extensions/rgb.py
- kmk/kmk_keyboard.py
- kmk/scheduler.py
- tests/keyboard_test.py
- tests/mocks.py
- tests/task.py
Let's abuse _asyncios TaskQueue to implement a very simple priority queue task scheduler.
Despite documentation, Circuitpython doesn't usually ship with a min-heap module; it does however implement a pairing-heap for `TaskQueue` in native code.
Why not use asyncio directly?
* all-out asyncio is a bit heavy,
* doesn't add a lot of usefull functionality in the case of the (mostly) sequential KMK,
* can be really difficult to grok for the causal user,
* would require extensive rewrites to benefit from.
An example of a periodically self-rescheduling task is included with the RGB extension.
> Enhancement heap scheduler

- kmk/quickpin/pro_micro/frood.py
Added quickpin support for Frood RP2040 Microcontroller by 42keebs (https://github.com/piit79/Frood)
Differs from other controllers supported by quickpin because it has 5 extra pins on the bottom like the Elite Pi. Unlike Elite Pi, it is supported by circuitpython, although the firmware should work on the Elite Pi and similar microcontrollers as well.
> Added quickpin support for Frood RP2040 Microcontroller

- docs/ja/Getting_Started.md
- docs/ptBR/Getting_Started.md
Links to `user_keymaps` were pointing to repository.
> Fixed user_keymaps dead links

- kmk/kmk_keyboard.py
`del` modifies the list being iterated over, resulting in skipping the exclusion of consecutive failed modules/extensions.
> Fix loop skip in `during_bootup`

- docs/en/boot.md
- kmk/bootcfg.py
Just an idea how to streamline (read: user-proof) common configurations that happen at boot time.
It this form, it would still have to be manually called in `boot.py`:
```python
import board
from kmk.bootcfg import bootcfg
bootcfg(board.GP0, no_cdc=False)
bootcfg(board.GP9, board.GP0, no_midi=False)
```
> Add boilerplate method for board configuration at boot time

- docs/en/boot.md
- docs/en/mouse_keys.md
- kmk/bootcfg.py
- kmk/hid.py
- kmk/hid_reports/pointer.py
- kmk/keys.py
- kmk/modules/mouse_keys.py
depends on #795 unfortunately.
Pointing device panning (aka horizontal scrolling), technically similar parts of #793, but created independently:
* new HID report, enabled through `bootcfg`
* new mouse keys
* docs
> Feature pointing device panning

- tests/test_holdtap.py
- tests/test_oneshot.py
Unit tests keep occasionally failing because of timing constraints.
These are trial-and-error values, may need adjusting in the future.
> Relax unit test timing conditions

- kmk/scheduler.py
Sorry, my bad. This was tied to #795, but I forgot to add a single commit. Happens if you work on 7 things at the same time.
predates / superseeds #803 & #804
resolves #805
> Add the ability to restart PeriodicTask

- kmk/scheduler.py
Fixed error (PeriodicTaskMeta has no ph_key) in get_due_task() when create_task argument is PeriodicTaskMeta.
> Fix create_task

- .github/workflows/compile.yml
This is a fairly trivial GH Action that automatically runs `make compile` and uploads the zip (for an example of what this looks like, see Artifacts [here](https://github.com/rrotter/kmk_firmware/actions/runs/5035251976)). As configured this will only run on merge/push to the master branch. Only supports CircuitPython 8, would be easy to add other versions if need be.
This was requested in #270.
> build zip of .mpy files with GitHub Action, resolve #270

- boards/sofle/sofleV2/README.md
- boards/sofle/sofleV2/kb.py
Updated Sofle's `kb.py` to use quickpin definitions for the pinout. Will make setting up Sofle for people with other MCU boards much less of a drag.
> Sofle quickpin

- boards/dactyl/README.md
- boards/dactyl_lightcycle/README.md
- boards/dactyl_manuform/README.md
- boards/dactyl_manuform_mini/README.md
update `readme.md` files of the following boards to include Dactyl Keyboard Configurator site information:
- dactyl
- dactyl_lightcycle
- dactyl_manuform
- dactyl_manuform_mini
> update dactyl readme file(s)

- boards/dactyl_manuform_carbonfet/4x5/kb.py
- boards/dactyl_manuform_carbonfet/4x5/main.py
- boards/dactyl_manuform_carbonfet/4x6/kb.py
- boards/dactyl_manuform_carbonfet/4x6/main.py
- boards/dactyl_manuform_carbonfet/5x6/kb.py
- boards/dactyl_manuform_carbonfet/5x6/main.py
- boards/dactyl_manuform_carbonfet/5x7/kb.py
- boards/dactyl_manuform_carbonfet/5x7/main.py
- boards/dactyl_manuform_carbonfet/6x6/kb.py
- boards/dactyl_manuform_carbonfet/6x6/main.py
- boards/dactyl_manuform_carbonfet/6x7/kb.py
- boards/dactyl_manuform_carbonfet/6x7/main.py
- boards/dactyl_manuform_carbonfet/README.md
Addition of the [carbonfet](https://github.com/carbonfet) thumb cluster variation of the dactyl_manuform to KMK
> Add `dactyl_manuform_carbonfet` board

- .github/ISSUE_TEMPLATE/config.yml
This PR adds links when creating new issues and disables the blank issue template.
I have linked the individual zulip streams in an effort to get discussions and conversations there, which is also why I disabled the blank issues.
I hope this solves #634 for the maintainers.
> Enhanced issue templates

- boards/ZFR_KBD/RP2.65-F/kb.py
- boards/sofle/sofleV2/kb.py
`DiodeOrientation` was moved into `kmk.scanners` in #386. Ran into an import that wasn't updated in the Sofle config, and found one more instance of it in another board config.
> Fix DiodeOrientation imports from matrix module

- kmk/quickpin/pro_micro/elite_pi.py
Add Quickpin Support for the [Elite Pi](https://splitkb.com/products/elite-pi) using [this](https://docs.keeb.io/elite-pi-guide) as a Reference.
> Added Quickpin for Elite Pi

- kmk/extensions/rgb.py
Use the selected Brightness (val) to determine the max brightness for breathing animations, rather than the max. 
Prevents me being blinded at night when I change animations.
> determine breath val on selected val

- kmk/extensions/display.py
Simple fix to make SSD1306 work again.
Adding `displayio.release_displays()` might be needed for other backends if user is experiencing `ValueError: pin in use` on soft reboot.
> Fix SSD1306

- .github/workflows/compile.yml
> feat: Only build mpy files when kmk library files changed

- kmk/extensions/rgb.py
resolves #368
`reverse_animation` has to be set explicitly at the boundaries.
> Fix RGB animation "knight"

- kmk/extensions/rgb.py
Based on the findings of #864. Fixes the underlying issue.
> Fix inconstistent PixelBuffer.auto_write handling

- kmk/modules/encoder.py
I ran into an issue with trying to use a rotary encoder through a GPIO expander module. These modules often give you access to their pins in the form of digitalio.DigitalInOut objects. I made a small adjustment to the Encoder module in KMK to support a pin being some form of DigitalInOut object rather than a microcontroller.Pin object.
Check if pin is a microcontroller.Pin. If it is, keep the old logic of turning it into a digitalio.DigitalInOut object. If it isn't, just assume it's already a DigitalInOut object and use it as is.
> Support bare DigitalInOut pins in Encoder module

- kmk/extensions/rgb.py
fix an issue with the Breathing animation where when the val is higher than val_limit it can hide all or parts of the animation
> clamp breathing brightness

- kmk/modules/adns9800.py
Added missing keyboard input arguments to the AX.X.move and AX.Y.move function calls.
I have an adns9800 module running on a Pi Pico which I have tested with this fix on, and it's working in my local copy.
I had gotten the adns9800 module working with an older version of kmk, but the latest version of kmk was throwing errors when moving the trackball on the adns9800, and this change fixes the issue for me.
> fix adns9800 module: add missing inputs to AX.X.move and AX.y.move

- .github/workflows/spellcheck.yml
Quick & dirty fix for the spellcheck action.
Not a very nice or efficient solution. While searching for ready-to-use aspell actions I stumbled across `pyspelling`, which could be worth a consideration as a replacement for our janky shell script.
> Fix aspell dependency in spellcheck action

- docs/en/encoder.md
- kmk/modules/encoder.py
Added support to Encoder.py to allow GPIOEncoder to accept tuple for pin_button construction.  This includes allowance for pull resistor (pullup/pulldown) customisation directly from code.py.  Additionally the change preserves state generation semantics for pin_button.get_value(self) and depends upon the pull direction.  The default pull direction remains as digitalio.Pull.UP
An example config from code.py to customise the pin button pull up direction:
encoder_handler.pins = ((board.VOLC_A, board.VOLC_B, (board.VOLC_PUSH, True, digitalio.Pull.DOWN), False, 2),)
Tested this out on my own code.py.
> Added extra construction support to Encoder.py to support pullup direction from Code.py

- kmk/extensions/rgb.py
Since the animate() method doesn't call `self.show()` when RGB is toggled off, it has to be called in `self.off()` for the latter to produce desired effect.
> Fix off() method in RGB

- kmk/modules/layers.py
- tests/keyboard_test.py
- tests/test_layers.py
* Fix bug where active layer list can become empty by combining MO and TO,
* add missing debug hook to `_to_pressed`,
* add some unit tests for the layer module,
* fix unit test result for empty reports.
> Fix bug where active layer list can become empty

- docs/en/debugging.md
- kmk/utils.py
- tests/mocks.py
- util/aspell.en.pws
Automatically enable debug output if a serial monitor is connected to the serial interface.
> Add automatic debug logs

- kmk/extensions/statusled.py
Fix for issue 913.
Renamed self._brightness to self.brightness
> #913 fix statusled extension variable name typo

- docs/en/config_and_keymap.md
- docs/en/holdtap.md
trying to clarify a few things that I stumbled on while learning kmk, split from https://github.com/KMKfw/kmk_firmware/pull/915
> minor doc updates

- boards/nullbitsco/README.md
- boards/nullbitsco/tidbit/README.md
- boards/nullbitsco/tidbit/kb.py
- boards/nullbitsco/tidbit/main.py
- kmk/quickpin/pro_micro/bitc_promicro.py
Split from https://github.com/KMKfw/kmk_firmware/pull/915 after review by board owner.  cc @jaygreco
> Mapping for nullbits tidbit board with bit-c pro

- boards/fingerpunch/ffkb/other_pro_micro/kb.py
- boards/gtips/reviung41/kb.py
- boards/kyria/kb_v1.py
- docs/en/porting_to_kmk.md
- docs/ptBR/porting_to_kmk.md
- kmk/scanners/__init__.py
Modified the board code that used intify_coordinates to use the same method as other boards to the best of my ability, removed the references to intify_coordinate in the "porting to kmk" documentation, and then removed the intify_coordinate method itself.
Resolves #922
> Removed intify_coordinate from code, boards, docs

- tests/mocks.py
This only affects testing and development: unit tests break if you put any temporary garbage collector calls in the code, for example for profiling.
> Fix missing gc mock

- docs/en/Display.md
A few tweaks to the example mentioned in the Display extension documentation.
- Moved the `device_address` argument from the `Display` instantiation to the `SSD1306` instantiation.  `Display` doesn't currently support this argument, but `SSD1306` does (https://github.com/KMKfw/kmk_firmware/blob/master/kmk/extensions/display.py#L137)
- Added missing comma to the arguments for the `Display` instantiation.
> Minor tweaks to the example in the Display extension doc

- kmk/scanners/digitalio.py
- tests/keyboard_test.py
Fixing the bug I introduced earlier. Not especially pretty, but this scanner's code is very hard to follow in general.
> Fix digitalio matrix orientation

- Makefile
Fixes issues with auto-discovery / order of mock imports (specifically #930).
As a side effect: speeds up unittesting.
> Fix unittest auto-discovery

- docs/en/Display.md
- kmk/extensions/display/__init__.py
- kmk/extensions/display/builtin.py
- kmk/extensions/display/sh1106.py
- kmk/extensions/display/ssd1306.py
A while ago, when I added the `BuiltInDisplay` backend in #846, I made an erroneous assumption about how the displays worked. I moved `displayio.release_displays()` to the `__init__()` methods of the displays that needed it, which inadvertently broke them. (Which I sincerely apologize for.)
This was later fixed in #871, at the cost of breaking `BuiltInDisplay`.
I have since come up with a compromise that should ensure all currently supported displays are functional: Break `display.py` into multiple files:
- `display.py`, which contains the classes for the displays that require `displayio.release_displays()`
- `display_builtin.py`, which contains `BuiltInDisplay`
- `display_common.py`, which contains the code shared by both, which is also re-exported by both of the other files for …
> Split display.py into files for each backend

- docs/en/boot.md
- docs/en/serialace.md
- kmk/bootcfg.py
- util/aspell.en.pws
Add data serial to bootcfg, rename console serial to distinguish between them.
Draft, because I have currently no clue why the spellchecker started complaining about a single code segment...
> Add data serial to `bootcfg` and rename console serial

- docs/en/layers.md
- kmk/modules/layers.py
- tests/test_layers.py
Reference: [chat discussion](https://kmkfw.zulipchat.com/#narrow/stream/384078-KMK-development/topic/adding.20an.20extra.20way.20of.20switching.20layers)
> Add a key for replacing the top layer

- docs/en/layers.md
- docs/en/pimoroni_trackball.md
- change for more descriptive paragraph subtitle
- introducing idea that also board's RGB status LED can be used for that purpose
- slightly expanded code snippet to make it copy-paste usable
- more comments in the code snippet about values range and their specifics
- slightly refactored code to add possibility to indicate only chosen layers
> Documentation update - activ layer rgb indication

- kmk/keys.py
This is a syntax error that just happened to not fail on CP < 9.x.
> Fix positional argument order in argumented keys

- Makefile
- tests/__init__.py
I had this issue a while back, where scanning the entire project for `test*.py` files caused problems in combination with the `TESTS` variable. To be honest, the details elude mit at this point in time -- but it probably doesn't hurt to restrict the test discovery? At least for me it worked well enough that I forgot to PR it.
> Make unittest only scan the `tests/` directory

- kmk/kmk_keyboard.py
Trigger a supervisor reload on any exception, restarting the firmware; unless it's a keyboard interrupt in which case we explicitly want to drop into the REPL.
Replace the sparse debug error message with a stacktrace.
> Implement automatic firmware reload and show error stacktrace

- docs/en/keys.md
- kmk/keys.py
I have only once seen a legitimate use case for these handlers -- one where custom handlers would've been a bit more complicated, and that use case was so niche that I can't remember what it was.
I don't think this functionality and the associated overhead should be the default for *every single key*.
Also: macros can replace this functionality without requiring users to learn how to make custom keys from scratch.
> Remove key pre/post handlers in favor of macros

- docs/en/boot.md
- kmk/bootcfg.py
There have been people complaining about windows occasionally "rebooting" their keyboard.
> Add boot configuration for autoreload when writing to the CP drive

- boards/pimoroni/keybow_2040/code.py
- boards/pimoroni/keybow_2040/keybow_2040_rgb.py
Replace slow RGB wrapper for is31fl3731 driver with a custom implementation which double-buffers with two frames and writes pixels in batches (or all 144 in bulk).
Speeds up default RGB breath effect from ~12FPS to ~60FPS.
Fixes #859.
> Keybow 2040: Speed up RGB.

- .github/workflows/compile.yml
- .github/workflows/spellcheck.yml
- .github/workflows/test.yml
Bump the versions of various actions to fix deprecation warnings, which appear in the Annotations section of workflow runs.
eg:
from: https://github.com/actions/upload-artifact/actions/runs/9477575562
> CI: Bump workflow action versions.

- kmk/keys.py
- kmk/modules/holdtap.py
- kmk/modules/layers.py
- kmk/modules/tapdance.py
Generating a debug message for every successfully instantiated key is excessively noisy and generally not helpfull. Similarly, indicating a failure to look up the hold-tap key when failure is the expected outcome, is not usefull information and has confused users in the past. (The HT check is not pretty, but necessary in order to bind `KC.HT` to `HoldTap` instead of modules inheriting the constructor, fyi)
This PR addresses both of those inconveniences.
> Improve key generation debug

- docs/en/README.md
- docs/en/modules.md
- docs/en/sticky_keys.md
- docs/en/tapdance.md
- kmk/modules/sticky_keys.py
- tests/test_sticky_keys.py
There was a thing that didn't work for me, and once again... as I came to realize, the current implementation based on modified hold-tap mechanism wasn't the best choice in the first place and increasingly difficult to work around.
* complete rewrite, basically from scratch
* rebranded to "sticky keys", because that is unarguably the more sensible name
* no more dependency on hold-tap
* actually helpful comments (I hope)
* works from tap dance, can even stack multiple sticky keys from a single tap dance
* even more tests
* new feature to stack with any other keys until all keys are released
The old `oneshot` module is still in place, can be cleaned up eventually.
> Refactor sticky/oneshot keys

- docs/en/keys.md
- kmk/extensions/display/__init__.py
- kmk/extensions/media_keys.py
- kmk/extensions/peg_rgb_matrix.py
- kmk/extensions/rgb.py
- kmk/handlers/stock.py
- kmk/hid.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/autoshift.py
- kmk/modules/capsword.py
- kmk/modules/combos.py
- kmk/modules/mouse_keys.py
- kmk/modules/power.py
- kmk/modules/string_substitution.py
- tests/test_autoshift.py
- tests/test_kmk_keys.py
- tests/test_string_substitution.py
Here's the beginning of something I wanted to do for a long time: Use pythons typing system to distinguish key types, i.e. use actual classes instead the self-made type system that compares fake key codes against `FIRST_KMK_INTERNAL_KEY`.
Also gone: secretly changing the meaning of keys with the `has_modifiers` attribute. Modified keys are now their own class, they work for any key (including for example mouse and media), not just keyboard HID -- a limitation that was never documented in the first place. Shifted keys are handled by the `ModifiedKeys` handlers and are no longer a special case deep inside `hid.py`, which will make resolving issues like #642 easier.
Coming soon: getting rid of `key.meta`, aka: "we already use classes for key types, but only sometimes, and we hide it behind a …
> Refactor key types

- docs/en/sticky_keys.md
- kmk/modules/sticky_keys.py
- tests/test_sticky_keys.py
An enhancement that makes it possible to release a sticky key by tapping it again -- useful when user only wants to tap a key(`KC.LGUI`) or simply changes their mind.
This behavior is enabled by default.
> Sticky keys: retap_cancel

- kmk/extensions/rgb.py
After upgrading to the latest version of KMK, I encountered this error: 
```
AttributeError: 'RGB' object has no attribute '_rgb_to'
```
It looks like `self._rgb_tog` was misspelled as `self._rgb_to`.
> Fix _rgb_tog

- kmk/modules/sticky_keys.py
- tests/test_sticky_keys.py
We actually missed a scenario: canceling a sticky key while one or more interrupting keys have already been pressed.
> Fix retap_cancel after interrupting key press

- kmk/keys.py
Apparently this syntax is fine with CP 9.x's mpy-cross, but not CP 8.x's.
> Fix syntax error with mpy-cross-8.x

- kmk/modules/combos.py
To prevent unconditional acess, this change checks if the `code` attribute actually exists and falls back to the key description.
> fixes #1005: Missing attribute `code` results in AttributeError

- tests/test_kmk_extension_stringy_keymaps.py
This didn't show up during test run of #1013, because the changes weren't in place yet.
> Fix unit test for string_keymaps

- kmk/kmk_keyboard.py
> bugfix: `KMKKeyboard.during_bootup` method

- kmk/modules/split.py
I just ran into an error on a split keyboard with direct pin wiring. when not having a coordmap yet (still testing the keys with the helper to log the keys coordmapping index) KMK would just error with "NoneType has no len()" this did not help me much in debugging this issue.
the cause was that with a custom scanner the keyboard.row_pins and keyboard.col_pins are not set and then the split during_bootup cannot guess a coordmap. I added a print statement that tells the user the coordmapping is missing when both of these are not defined on the keyboard as either the pins are required or the coordmap.
> log error when the coordmapping is not guessable

- docs/en/combo_layers.md
changes fixes a minor typo in the example by changing KC.8 to KC.N8
> Fix typo in combo_layers.md

- docs/en/combo_layers.md
When I first wrote this doc, I made a ton of mistakes. I came back to it to clean it up a bit, and it should make more sense now.
> Fixed grammatical mistakes, added clarification

- docs/en/oneshot.md
- kmk/modules/oneshot.py
added docstring to oneshot.py
added deubug message in module's __init__
changed docs to made deprecation of oneshot keys clear and to remove ambiguity with sticky keys.
made changes based on comments found 
here  #978 
and [on Zulip](https://kmkfw.zulipchat.com/#narrow/stream/358347-general/topic/Extensions.20not.20working.20for.20mini.20keyboard/near/447140514)
> Document deprecation of OneShot keys

- kmk/modules/rapidfire.py
- tests/test_rapidfire.py
* Fix RapidFireKey argument expansion
* Add basic unit test
* Fix calling keyboard.tap() from within a scheduled task
* Simplify code and memory management
> Refactor RapidFire

- docs/en/keycodes.md
- kmk/keys.py
> Deduplicate international keys

- docs/en/keys.md
- docs/en/macros.md
- util/aspell.en.pws
A suggestion for documentation about:
* how to use custom keys
* when and why to prefer them over macros
> Add documentation for custom keys

- docs/en/scanners.md
- kmk/scanners/keypad.py
- util/aspell.en.pws
This is needed for proper debouncing
> Allow passing debounce_threshold in keypad.py

- boards/atreus62/main.py
- boards/crowboard/main.py
- boards/fingerpunch/ffkb/nice_nano/main.py
- boards/fingerpunch/ffkb/other_pro_micro/main.py
- boards/keebio/iris/main.py
- boards/kyria/main.py
- boards/splitkb/aurora/lily58/main.py
- docs/en/config_and_keymap.md
- docs/en/debugging.md
- docs/en/encoder.md
- docs/en/extension_stringy_keymaps.md
- docs/en/keycodes.md
- kmk/extensions/led.py
- kmk/extensions/peg_rgb_matrix.py
- kmk/extensions/statusled.py
- kmk/handlers/stock.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/adns9800.py
- kmk/modules/encoder.py
- kmk/modules/midi.py
- kmk/modules/split.py
- kmk/utils.py
- tests/keyboard_test.py
* Use the debug utility everywhere.
* Guard all debug statements.
* Remove the legacy `keyboard.debug_enabled` flag / property,
* and document debug utility usage instead
> Cleanup debug

- boards/atreus62/main.py
- boards/fingerpunch/ffkb/other_pro_micro/main.py
- boards/keebio/iris/main.py
- boards/lunakey_pico/main.py
- docs/en/config_and_keymap.md
- docs/en/encoder.md
> Cleanup legacy `keyboard.tap_time`

- docs/en/boot.md
- kmk/bootcfg.py
Initially bootcfg was all or nothing, this is no longer the case. Value of the sense pin currently only affects serial console and storage, but user might not even be interested in disabling those. No reason to lock stuff like NKRO behind this piece of configuration.
> Make bootcfg sense optional

- .devcontainer/devcontainer.json
- kmk/hid.py
HID classes now can create periodic tasks that check for connection and after its status has changed, re-run parts of code as needed.
> Enhancement: HID watchdog

- boards/anavi/knob1/README.md
- boards/anavi/knob1/code.py
This GitHub pull request brings the following changes for ANAVI Knob 1:
- boards/anavi/knob1/code.py: Add a new feature to support a mini OLED I2C SSD1306 display.
- boards/anavi/knob1/README.md: Add information about the Display extension for ANAVI Knob 1.
> ANAVI Knob 1: Add Support for OLED I2C SSD1306 Display

- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/string_substitution.py
- tests/test_autoshift.py
- tests/test_kmk_keys.py
- tests/test_string_substitution.py
fixes #642
This introduces a mechanism that distinguishes between explicit (`KC.LSFT`) and implicit (`KC.LSFT(KC.EQL)` == `KC.PLUS`) modifiers.
> Fix ModifiedKey roll-interaction with non-modified keys

- kmk/hid.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- kmk/modules/autoshift.py
- tests/keyboard_test.py
- tests/mocks.py
- tests/test_autoshift.py
This is a big one. It started out as smaller atomic commits, but the recent #1061 made a clean rebase a bad decision from the perspective of time and effort that would have been spent on it.
Summary:
* Small memory and performance improvements, mostly const() and bytearray ops.
* Separate out report specific code into report classes. Serves as a base for easier addition of custom endpoints in "the future".
* Lots of small integration changes, for example a simpler mechanism to record reports for unit tests (now with potential to verify other reports than 6KRO).
> Refactor hid.py

- boards/anavi/knobs3/README.md
- boards/anavi/knobs3/code.py
Hi,
This GitHub pull request adds SSD1306 I2C display support for ANAVI Knobs 3 with the following commits:
* boards/anavi/knobs3/code.py: Add a new feature to support a mini OLED I2C SSD1306 display.
* boards/anavi/knobs3/README.md: Add information about the Display extension for ANAVI Knobs 3.
Best regards, Leon
> ANAVI Knobs 3: Support SSD1306 I2C OLED Display

- kmk/keys.py
- tests/test_kmk_keys.py
inspired by: https://kmkfw.zulipchat.com/#narrow/channel/358347-general/topic/Issue.20with.20Shift.20Modifier.20Behavior.20When.20Typing.20Quickly
> Fix ModifiedKey roll-interaction with same non-modified keys

- docs/en/scanners.md
10 ms * 5 is truly horrific. 1 ms * 5 is what I've been using.
> Fix a mistake scanners.md

- docs/en/macros.md
- kmk/modules/macros.py
- util/aspell.en.pws
It started out as a fix to the documentation from [zulip](https://kmkfw.zulipchat.com/#narrow/channel/358347-general/topic/How.20to.20send.20arbitrary.20key.3F/near/496083132), and here we are.
> Enable recursion for callables in macros

- boards/a_dux/kb.py
- boards/anavi/anavi-arrows/arrows.py
- boards/boardsource/Lulu/kb.py
- boards/budgy/kb.py
- boards/draculad/kb.py
- boards/ferris_sweep/kb.py
- boards/isopad/kb.py
- boards/nullbitsco/tidbit/kb.py
- boards/pimoroni/keybow/keybow.py
- boards/pimoroni/keybow_2040/keybow_2040.py
- boards/zodiark/kb.py
- docs/en/scanners.md
- kmk/kmk_keyboard.py
KMKKeyboard has used class attributes instead of instance attributes. That is fundamentally incorrect, but hasn't caused issues in situ, where there's only ever one keyboard instance and the VM is reset with each restart.
It does however cause issues in unit tests, where erroneous internal states can bleed over from failed tests to normally passing tests.
> fix(KMKKeyboard)!: use __init__ to initialize the keyboard class

- docs/en/analogin.md
- kmk/modules/analogin.py
- util/aspell.en.pws
Draft of a better analog input module as mentioned in #638.
> Implement generalized analog input module

- boards/helix/README.md
- boards/nullbitsco/tidbit/README.md
- docs/en/pimoroni_trackball.md
Regardless of wether kmkfw.io is coming back (unlikely), these links should have been pointing to relative *.md anyway.
> doc: change dead links from kmkfw.io to repo docs

- kmk/hid.py
`_connected` was recently refactored out in hid.py however there was one that remained. This caused a crash on my board. After checking out the code and making the included change, changing this line to refer to `connected` works.
> small BLE fix on hid.py

- docs/en/mouse_keys.md
I noticed some formatting fixes when creating the SpacemouseKeys documentation (#1093), as well as a broken boot.md link.
> MouseKeys docs formatting

- kmk/modules/combos.py
- tests/test_combos_sticky_keys.py
This is necessary in order for other processing modules (sticky keys, holdtap, etc.) to see the combo result as a "regular" key event.
> fix(combo): emit result to processing pipeline

- boards/psion/layout_swe.py
Found a key missing from the layout during testing of new hardware
> Add missing keycode för 'Ä' key

- docs/en/boot.md
- kmk/bootcfg.py
- util/aspell.en.pws
This will make overriding vid/pid in #1092 a lot simpler and nicer.
> feat(bootcfg): set usb identification with a kwargs-dict

- docs/en/boot.md
- kmk/bootcfg.py
- kmk/hid.py
- kmk/hid_reports/six_axis.py
- kmk/keys.py
- kmk/kmk_keyboard.py
- util/aspell.en.pws
This is a chunk of  #1087.
This PR contains the SpaceMouse Compact-compatible HID implementation and updated boot.md documentation.
> Implement Six Axis HID

- docs/en/modules.md
- docs/en/spacemouse_keys.md
- kmk/modules/spacemouse_keys.py
This is a chunk of  #1087 for a module that
- Adds the 2 buttons found on a SpaceMouse Compact.
- Adds buttons for increasing/decreasing movement in the 6 axes.
PR dependencies: #1092
> SpacemouseKeys module

- docs/en/modules.md
- docs/en/mouse_jiggler.md
- kmk/modules/mouse_jiggler.py
This pull request adds a new module to periodically move the mouse cursor, keeping the host system awake.
> Add Mouse Jiggler module

- docs/en/encoder.md
the example provided in the encoder.md uses media_keys extension but the extension is not imported or appended
> added the media_keys extension import in encoder.md example
